<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Sistema de Administração de Condomínios</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="icon" type="image/png" href="images/icons/favicon.ico" />
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="bower_components/Ionicons/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="dist/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="dist/css/skins/_all-skins.min.css">
  <!-- Morris chart -->
  <link rel="stylesheet" href="bower_components/morris.js/morris.css">
  <!-- jvectormap -->
  <link rel="stylesheet" href="bower_components/jvectormap/jquery-jvectormap.css">
  <!-- Date Picker -->
  <link rel="stylesheet" href="bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="bower_components/bootstrap-daterangepicker/daterangepicker.css">
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
  <!--===============================================================================================-->
  
  <!--===============================================================================================-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

  <!--===============================================================================================-->
  <script src="bower_components/jquery/dist/jquery.min.js"></script>
  
  <!--===============================================================================================-->

</head>

<body style="background-color: #ecf0f5" class="hold-transition skin-black sidebar-mini teste">

  <div class="box">
            <div class="box-header">
              <h3 class="box-title"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Tabela de largura total listrada</font></font></h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body no-padding">
              <table class="table table-striped">
                <tbody><tr>
                  <th style="width: 10px"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Data Pagamento</font></font></th>
                  <th><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Codigo Boleto</font></font></th>
                  <th><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Valor Pago</font></font></th>                  
                </tr>
                <tr>
                  <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">1</font></font></td>
                  <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Atualizar o software</font></font></td>
                  <td>
                    <div class="progress progress-xs">
                      <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                    </div>
                  </td>
                  <td><span class="badge bg-red"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">55%</font></font></span></td>
                </tr>
                <tr>
                  <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2</font></font></td>
                  <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Banco de dados limpo</font></font></td>
                  <td>
                    <div class="progress progress-xs">
                      <div class="progress-bar progress-bar-yellow" style="width: 70%"></div>
                    </div>
                  </td>
                  <td><span class="badge bg-yellow"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">70%</font></font></span></td>
                </tr>
                <tr>
                  <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">3</font></font></td>
                  <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Cron job running</font></font></td>
                  <td>
                    <div class="progress progress-xs progress-striped active">
                      <div class="progress-bar progress-bar-primary" style="width: 30%"></div>
                    </div>
                  </td>
                  <td><span class="badge bg-light-blue"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">30%</font></font></span></td>
                </tr>
                <tr>
                  <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">4</font></font></td>
                  <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Corrigir e esmagar erros</font></font></td>
                  <td>
                    <div class="progress progress-xs progress-striped active">
                      <div class="progress-bar progress-bar-success" style="width: 90%"></div>
                    </div>
                  </td>
                  <td><span class="badge bg-green"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">90%</font></font></span></td>
                </tr>
              </tbody></table>
            </div>
            <!-- /.box-body -->

            <div style="width: 50%; margin: 20px">
              <button type="button" class="btn btn-block btn-success btn-flat"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Adicionar</font></font></button>
            </div>
  </div
</body>


  <!-- jQuery UI 1.11.4 -->
  <script src="bower_components/jquery-ui/jquery-ui.min.js"></script>
  <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
  <script>
    $.widget.bridge('uibutton', $.ui.button);
  </script>
  <!-- Bootstrap 3.3.7 -->
  <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
  <!-- Morris.js charts -->
  <script src="bower_components/raphael/raphael.min.js"></script>
  <script src="bower_components/morris.js/morris.min.js"></script>
  <!-- Sparkline -->
  <script src="bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
  <!-- jvectormap -->
  <script src="plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
  <script src="plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
  <!-- jQuery Knob Chart -->
  <script src="bower_components/jquery-knob/dist/jquery.knob.min.js"></script>
  <!-- daterangepicker -->
  <script src="bower_components/moment/min/moment.min.js"></script>
  <script src="bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
  <!-- datepicker -->
  <script src="bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
  <!-- Bootstrap WYSIHTML5 -->
  <script src="plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
  <!-- Slimscroll -->
  <script src="bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
  <!-- FastClick -->
  <script src="bower_components/fastclick/lib/fastclick.js"></script>
  <!-- AdminLTE App -->
  <script src="dist/js/adminlte.min.js"></script>
  <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
  <script src="dist/js/pages/dashboard.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="dist/js/demo.js"></script>
  <!--===============================================================================================-->  
</html>