<!--?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();       
?-->

<script>



</script>
 


<section class="content-header">
  <h1>
    Controle de Adimplência    
  </h1>
</section>
<section class="content">
     
<div>

  <form class="expanding-search-form">
  <div class="search-dropdown">
    <button class="button dropdown-toggle" type="button">
      <span class="toggle-active">Filtro</span>
      <span class="ion-arrow-down-b"></span>
    </button>
    <ul class="dropdown-menu">
      <li><a href="#">Unidade(Apto/Bloco)</a></li>
      <li><a href="#">Período(Mês/Ano)</a></li>
      <li><a href="#">Código(CódigoBoleto)</a></li>
    </ul>
  </div>
  <input class="search-input" id="global-search" type="search" placeholder="Consulta">
  <label class="search-label" for="global-search">
		    <span class="sr-only">Global Search</span>
	  </label>
  <button class="button search-button" type="button">
		    <span class="icon ion-search">
			      <span class="sr-only">Search</span>
		    </span>
	  </button>
</form>
</div>
    
  
  
       
  <div class="box">
    <div class="box-header">
      <h3 class="box-title"></h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body no-padding">
    <div id="encontrarPrevisao" >
              <!--Tabela-->
              <div class="table-responsive">
                <table class="table table-striped no-margin">
                  <thead>
                  <tr>
                    <th>AP-Bloco</th>
                    <th>Código</th>
                    <th>Valor Pago</th>
                    <th>Data de Emissão</th>
                    <th>Data de Pagamento</th>                    
                    <th><button type="button" title="Novo"     style="padding:5px; width:auto; float: left;" class="btn btn-success"><i class="fa fa-fw fa-plus"></i></button></th>
                  </tr>
                </thead>
                <tbody id="bodyTable">
                  <tr>
                    <td>101-A</td>
                    <td>123HRD123123</td>
                    <td>150,00</td>
                    <td>18/10/2018</td>
                    <td>21/11/2018</td>                    
                    <td>                      
                    <button type="button" title="Editar" style="padding:1px; width:auto; float: left; margin-right:10px;" class="btn btn-primary"><i class="fa fa-fw fa-edit"></i></button>
                    <button type="button" title="Gerar Boleto" style="padding:1px; width:auto; float: left;" class="btn btn-danger"><i class="fa fa-fw  fa-file-text-o "></i></button>
                    </td>
                  </tr>
                  <tr>
                    <td>307-B</td>
                    <td>421RD1235563</td>
                    <td>135,00</td>
                    <td>18/10/2018</td>
                    <td>29/11/2018</td> 
                    <td>                      
                      <button type="button" title="Editar" style="padding:1px; width:auto; float: left; margin-right:10px;" class="btn btn-primary"><i class="fa fa-fw fa-edit"></i></button>
                      <button type="button" title="Gerar Boleto" style="padding:1px; width:auto; float: left;" class="btn btn-danger"><i class="fa fa-fw  fa-file-text-o "></i></button>
                    </td>
                  </tr>
                  <tr>
                    <td>505-C</td>
                    <td>333HRD123123</td>
                    <td>142,00</td>
                    <td>18/10/2018</td>
                    <td>15/11/2018</td>
                    <td>                      
                    <button type="button" title="Editar" style="padding:1px; width:auto; float: left; margin-right:10px;" class="btn btn-primary"><i class="fa fa-fw fa-edit"></i></button>
                    <button type="button" title="Gerar Boleto" style="padding:1px; width:auto; float: left;" class="btn btn-danger"><i class="fa fa-fw  fa-file-text-o "></i></button>
                    </td>
                    
                  </tr>
                  <tr>
                     <td>401-D</td>
                     <td>123HRD123123</td>
                     <td>129,00</td>
                     <td>18/10/2018</td>
                     <td>26/11/2018</td>
                      <td>                      
                      <button type="button" title="Editar" style="padding:1px; width:auto; float: left; margin-right:10px;" class="btn btn-primary"><i class="fa fa-fw fa-edit"></i></button>
                    <button type="button" title="Gerar Boleto" style="padding:1px; width:auto; float: left;" class="btn btn-danger"><i class="fa fa-fw  fa-file-text-o "></i></button>
                      </td>
                    </tr>
                </tbody>                
                </table>
              </div>
            </div>
    </div>
    <!-- /.box-body -->

    

      
      <!-- /.box-tools -->
    </div>
  
          
  </section>