<!--?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();       
?-->

<script>



</script>
 


<section class="content-header">
  <h1>
    Controle de Adimplência    
  </h1>
</section>
<section class="content">
  <div class="row"> 

    <!-- Início Consulta-->
    <div class="col-xs-2" style="width: 450px;">
      <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="box-title">Pesquisar</h3>                      
        </div>
        <div class="box-body">
          <div class="col-md-16">
            <!-- Início Grupo-->
            <div class="form-group consulta-group">
              <div class="input-group">
                <!-- Início Filtro-->
                <div class="input-group-btn">
                  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <span class="toggle-active">Unidade</span>
                    <span class="fa fa-caret-down"></span>
                  </button>
                  <ul class="dropdown-menu">
                    <li class="menu-active" ><a href="/" onclick='$("#global-search").attr("placeholder", "AP-Bloco")'>Unidade</a></li>
                    <li><a href="/" onclick='$("#global-search").attr("placeholder", "Mes/Ano")'>Período</a></li>
                    <li><a href="/" onclick='$("#global-search").attr("placeholder", "NossoCodigo")'>Código</a></li>
                  </ul>
                </div>
                <!-- Fim Filtro-->
                <!-- Input consulta-->
                <input type="text" class="form-control search-input" id="global-search" type="search" placeholder="AP-Bloco">
                <!-- Botão consulta-->
                <span class="input-group-btn">
                  <button type="button" class="btn btn-primary" style="border-radius: 0 4px 4px 0;"><i class="fa fa-fw  fa-search"></i></button>
                </span>
                <div class="row" style="width: 40px; float:left; margin-left:10px;">
                  <button type="button" title="Imprimir" class="btn btn-block btn-info"><i class="fa fa-print"></i></button>              
                </div>     
              </div>              
            <!-- Fim Botões-->    
            </div>
           <!-- Fim Grupo-->                                
          </div>          
          </div>
        </div>
      </div>
      <!-- Fim Consulta-->
    </div> 
              
  <div class="box">
    <div class="box-header">
      <h3 class="box-title"></h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body no-padding">
    <div id="encontrarPrevisao" >
              <!--Tabela-->
              <div class="table-responsive">
                <table class="table table-striped no-margin">
                  <thead>
                  <tr>
                    <th>AP-Bloco</th>
                    <th>Código</th>
                    <th>Valor Pago</th>
                    <th>Data de Emissão</th>
                    <th>Data de Pagamento</th>                    
                    <th><button type="button" title="Novo"     style="padding:5px; width:auto; float: left;" class="btn btn-success"><i class="fa fa-fw fa-plus"></i></button></th>
                  </tr>
                </thead>
                <tbody id="bodyTable">
                  <tr>
                    <td>101-A</td>
                    <td>123HRD123123</td>
                    <td>150,00</td>
                    <td>18/10/2018</td>
                    <td>21/11/2018</td>                    
                    <td>                      
                    <button type="button" title="Editar" style="padding:1px; width:auto; float: left; margin-right:10px;" class="btn btn-primary"><i class="fa fa-fw fa-edit"></i></button>
                    </td>
                  </tr>
                  <tr>
                    <td>307-B</td>
                    <td>421RD1235563</td>
                    <td>135,00</td>
                    <td>18/10/2018</td>
                    <td>29/11/2018</td> 
                    <td>                      
                      <button type="button" title="Editar" style="padding:1px; width:auto; float: left; margin-right:10px;" class="btn btn-primary"><i class="fa fa-fw fa-edit"></i></button>
                    </td>
                  </tr>
                  <tr>
                    <td>505-C</td>
                    <td>333HRD123123</td>
                    <td>142,00</td>
                    <td>18/10/2018</td>
                    <td>15/11/2018</td>
                    <td>                      
                    <button type="button" title="Editar" style="padding:1px; width:auto; float: left; margin-right:10px;" class="btn btn-primary"><i class="fa fa-fw fa-edit"></i></button>                    
                    </td>
                    
                  </tr>
                  <tr>
                     <td>401-D</td>
                     <td>123HRD123123</td>
                     <td>129,00</td>
                     <td>18/10/2018</td>
                     <td>26/11/2018</td>
                      <td>                      
                      <button type="button" title="Editar" style="padding:1px; width:auto; float: left; margin-right:10px;" class="btn btn-primary"><i class="fa fa-fw fa-edit"></i></button>                    
                      </td>
                    </tr>
                </tbody>                
                </table>
              </div>
            </div>
    </div>
    <!-- /.box-body -->

    

      
      <!-- /.box-tools -->
    </div>
  
          
  </section>