<?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();
    $contatos = $valores['user'];  
    $condominio = $valores['cond'];  
?>
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Sistema de Administração de Condomínios</title>


  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="icon" type="image/png" href="Views/Sistema/Admin/images/icons/favicon.ico" />

  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="Views/Sistema/Admin/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!--Bootstrap-Combobox-->
  <link rel = "stylesheet" href ="Views/Sistema/Admin/bower_components/bootstrap-combobox/css/bootstrap-combobox.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="Views/Sistema/Admin/bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="Views/Sistema/Admin/bower_components/Ionicons/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="Views/Sistema/Admin/dist/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Está usando skin-black -->
  <link rel="stylesheet" href="Views/Sistema/Admin/dist/css/skins/skin-black.min.css">
  <!-- Morris chart -->
  <link rel="stylesheet" href="Views/Sistema/Admin/bower_components/morris.js/morris.css">  
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="Views/Sistema/Admin/css/style_css.css">
  <link rel="stylesheet" type="text/css" href="Views/css/global_css.css">
  <!--===============================================================================================-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
     
</head>

<body class="hold-transition skin-black sidebar-mini">

  <div class="wrapper">
    <header class="main-header">

      <!-- Logo -->
      <a class="logo" href="/" onClick='requisitarServidor("index.php", "Inicio.listar", "", "body_resposta"); return false;'>
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>C<span style="color:#0f8cd6">A</span>O</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><img style="width: 20px;" src="Views/Sistema/Admin/images/icons/favicon.ico" alt="Cazulo"> C<span style="color:#0f8cd6">azul</span>o</span>
      </a>
      <!-- Header Navbar: style can be found in header.less -->
      <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
          <span class="sr-only">Toggle navigation</span>
        </a>

        <div style="float: left; margin-left:20px; min-width: 30vw;" >
          <ul class="nav navbar-nav " style="width: 100%;">
            <div class="input-group input-group-sm selecEmpresa">
              <input type="text" class="form-control" id="selectCond" placeholder="Selecione um Condomínio" disabled value="<?= $condominio?>">              
              <span class="input-group-btn">
                <button type="button" class="btn btn-primary btn-flat" onClick='requisitarServidor("index.php", "Condominios.selecionar", "", "modal_resposta"); return false;'><i class="fa fa-building"></i></button>
              </span>
            </div>
          </ul>
        </div>

        <div class="navbar-custom-menu">
          <ul class="nav navbar-nav">

            <!-- User Account: style can be found in dropdown.less -->
            <li class="dropdown user user-menu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <img src="Views/Sistema/Admin/images/icons/favicon.ico" class="user-image" alt="User Image">
                <span class="hidden-xs"><?=$valores['user']['nome']; ?></span>
              </a>
              <ul class="dropdown-menu">
                <!-- User image -->
                <li class="user-header">
                  <img src="<?=$valores['user']['imagem']; ?>" class="img-circle" alt="User Image">

                  <p>
                  <?=$valores['user']['nome']; ?> - <?=$valores['user']['perfilAcesso']; ?>
                    <small><?=$valores['user']['usuario']; ?></small>
                  </p>
                </li>
                <!-- Menu Footer-->
                <li class="user-footer">
                  <div class="pull-left">
                    <a href="#" class="btn btn-default btn-flat">Alterar Senha</a>
                  </div>
                  <div class="pull-right">
                    <a onClick='requisitarServidor("index.php", "Login.logoff", "", "body_resposta"); return false;' class="btn btn-default btn-flat">Sair</a>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
      <!-- sidebar: style can be found in sidebar.less -->
      <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
          <div class="pull-left image">
            <img src="Views/Sistema/Admin/images/icons/favicon.ico" class="img-circle" alt="User Image">
          </div>
          <div class="pull-left info">
            <p><?=$valores['user']['nome']; ?></p>
          </div>
        </div>

        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
          <li class="header">MENU</li>
 
          <?php if(in_array("PrestacaoContas",$valores['user']['permissao'])){?>      <li><a href="/" onClick='requisitarServidor("index.php", "PrestacaoContas.listar", "titulo=Prestação de Contas", "body_resposta"); return false;'><i class="fa fa-book"></i> <span>Prestação de Contas</span></a></li>                  <?php }?>
          <?php if(in_array("PrevisaoDespesas",$valores['user']['permissao'])){?>     <li><a href="/" onClick='requisitarServidor("index.php", "PrevisaoDespesas.listar", "titulo=Previsão de Despesas", "body_resposta"); return false;'><i class="fa fa-file-powerpoint-o"></i> <span>Previsão de Despesas</span></a></li>  <?php }?>          
          <?php if(in_array("TaxaCondominio",$valores['user']['permissao'])){?>       <li><a href="/" onClick='requisitarServidor("index.php", "TaxaCondominio.listar", "titulo=Taxa de Condomínio", "body_resposta"); return false;'><i class="fa fa-barcode"></i> <span>Taxa de Condomínio</span></a></li>                  <?php }?>
          <?php if(in_array("ControleAdimplencia",$valores['user']['permissao'])){?>  <li><a href="/" onClick='requisitarServidor("index.php", "ControleAdimplencia.listar", "titulo=Controle de Adimplência", "body_resposta"); return false;'><i class="fa fa-money"></i> <span>Controle de Adimplência</span></a></li>     <?php }?>

          <li class="header">Extras</li>
          
          <?php if(in_array("Condominio",$valores['user']['permissao'])){?><li><a href="/" onClick='requisitarServidor("index.php", "Condominios.listar", "titulo=Condomínio", "body_resposta"); return false;'><i class="fa fa-building-o"></i> Condomínio</a></li>  <?php }?>         
          <?php if(in_array("Categoria",$valores['user']['permissao'])){?><li><a href="/" onClick='requisitarServidor("index.php", "Categoria.listar", "titulo=Categoria", "body_resposta"); return false;'><i class="fa fa-folder-open-o"></i> Categoria</a></li> <?php }?>
          <?php if(in_array("Usuarios",$valores['user']['permissao'])){?> <li><a href="/" onClick='requisitarServidor("index.php", "Usuarios.listar", "titulo=Usuários", "body_resposta"); return false;'><i class="fa fa-users"></i> <span>Usuários</span></a></li> <?php }?>
          
        </ul>
      </section>
      <!-- /.sidebar -->
    </aside>

    <!-- Div resposta modal-->            
    <div id="modal_resposta"></div> 

    <!-- Div resposta corpo página -->            
    <div class="content-wrapper" id="body_resposta"></div>
    <div id="load_div"></div>
    

    <!-- /.content-wrapper -->
    <footer class="main-footer">
      <div class="pull-right hidden-xs">
        <b>Versão</b> 1.0.2
      </div>
      <strong>Copyright &copy; 2018 <a target="_blank" href="https://jonassuncao.github.io/">@Jônathas Assunção</a> | <a target="_blank" href="https://dominicrp.github.io/">@Dominic Rocha</a> | <a target="_blank" href="https://davidbarros.github.io/">@David
          Antônio</a> | <a target="_blank" href="https://jaderhfa.github.io/">@Jader Henrique</a>.</strong> All rights
      reserved.
    </footer>


  </div>
  
  <!-- jQuery 3 -->
  <script src="Views/Sistema/Admin/bower_components/jquery/dist/jquery.min.js"></script>    
  <!-- Bootstrap 3.3.7 -->
  <script src="Views/Sistema/Admin/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
  <!-- Morris.js charts -->
  <script src="Views/Sistema/Admin/bower_components/raphael/raphael.min.js"></script>
  <script src="Views/Sistema/Admin/bower_components/morris.js/morris.min.js"></script>
  <!-- datepicker -->
  <script src="Views/Sistema/Admin/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>  
  <!-- iCheck 1.0.1 -->
  <script src="Views/Sistema/Admin/plugins/iCheck/icheck.min.js"></script>
  <!-- AdminLTE  -->  
  <script src="Views/Sistema/Admin/dist/js/adminlte.min.js"></script>

  <script src="Views/js/global_js.js"></script>
  <script src="Views/Sistema/Admin/js/login_js.js"></script>
  <script src="Views/Sistema/Admin/js/script_js.js"></script>
  <script>
    //Verifica se o #body_resposta está vazio, caso esteja vazio... Coloca a página inicial
    if($('#body_resposta').html() == '') requisitarServidor("index.php", "Inicio.listar", "titulo=Início", "body_resposta");
  </script>
  <!--===============================================================================================-->  
  
</body>

</html>