<?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();
    $contatos = $valores['user'];  
    $condominio = $valores['cond'];  
?>
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Sistema de Administração de Condomínios</title>


  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="icon" type="image/png" href="Views/Sistema/admin/images/icons/favicon.ico" />
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="Views/Sistema/admin/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!--Bootstrap-Combobox-->
  <link rel = "stylesheet" href ="Views/Sistema/admin/bower_components/bootstrap-combobox/css/bootstrap-combobox.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="Views/Sistema/admin/bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="Views/Sistema/admin/bower_components/Ionicons/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="Views/Sistema/admin/dist/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="Views/Sistema/admin/dist/css/skins/_all-skins.min.css">
  <!-- Morris chart -->
  <link rel="stylesheet" href="Views/Sistema/admin/bower_components/morris.js/morris.css">
  <!-- jvectormap -->
  <link rel="stylesheet" href="Views/Sistema/admin/bower_components/jvectormap/jquery-jvectormap.css">
  <!-- Date Picker -->
  <link rel="stylesheet" href="Views/Sistema/admin/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="Views/Sistema/admin/bower_components/bootstrap-daterangepicker/daterangepicker.css">
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="Views/Sistema/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
  <!-- iCheck for checkboxes and radio inputs -->
  <link rel="stylesheet" href="Views/Sistema/admin/plugins/iCheck/all.css">  
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="Views/Sistema/admin/css/style_css.css">
  <link rel="stylesheet" type="text/css" href="Views/css/global_css.css">
  <!--===============================================================================================-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
  
  <!--===============================================================================================-->
  <script src="Views/Sistema/admin/bower_components/jquery/dist/jquery.min.js"></script>
  <!--===============================================================================================-->
   
</head>

<body class="hold-transition skin-black sidebar-mini">

  <div class="wrapper">
    <header class="main-header">

      <!-- Logo -->
      <a class="logo" href="/" onClick='Envio_Ajax("POST", "body_resposta", "load_div", "Home", "exibir","opc=inicio&act=listar&desc=inicio"); return false;'>
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>C<span style="color:#0f8cd6">A</span>O</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><img style="width: 20px;" src="Views/Sistema/admin/images/icons/favicon.ico" alt="Cazulo"> C<span style="color:#0f8cd6">azul</span>o</span>
      </a>
      <!-- Header Navbar: style can be found in header.less -->
      <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
          <span class="sr-only">Toggle navigation</span>
        </a>

        <div style="float: left; margin-left:20px; min-width: 30vw;" >
          <ul class="nav navbar-nav " style="width: 100%;">
            <div class="input-group input-group-sm selecEmpresa">
              <input type="text" class="form-control" id="selectCond" placeholder="Selecione um Condomínio" disabled value="<?= $condominio?>">              
              <span class="input-group-btn">
                <button type="button" class="btn btn-primary btn-flat" onClick='Envio_Ajax("POST", "modal_resposta", "load_div", "Home", "exibir","opc=condominios&act=selecionar&desc=Condomínios"); return false;'><i class="fa fa-building"></i></button>
              </span>
            </div>
          </ul>
        </div>

        <div class="navbar-custom-menu">
          <ul class="nav navbar-nav">

            <!-- User Account: style can be found in dropdown.less -->
            <li class="dropdown user user-menu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <img src="Views/Sistema/admin/images/icons/favicon.ico" class="user-image" alt="User Image">
                <span class="hidden-xs"><?=$valores['user']['nome']; ?></span>
              </a>
              <ul class="dropdown-menu">
                <!-- User image -->
                <li class="user-header">
                  <img src="<?=$valores['user']['imagem']; ?>" class="img-circle" alt="User Image">

                  <p>
                  <?=$valores['user']['nome']; ?> - <?=$valores['user']['perfilAcesso']; ?>
                    <small><?=$valores['user']['usuario']; ?></small>
                  </p>
                </li>
                <!-- Menu Footer-->
                <li class="user-footer">
                  <div class="pull-left">
                    <a href="#" class="btn btn-default btn-flat">Alterar Senha</a>
                  </div>
                  <div class="pull-right">
                    <a onClick='Envio_Ajax("POST", "body_resposta", "load_div", "Login", "logoff", ""); return false;' class="btn btn-default btn-flat">Sair</a>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
      <!-- sidebar: style can be found in sidebar.less -->
      <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
          <div class="pull-left image">
            <img src="Views/Sistema/admin/images/icons/favicon.ico" class="img-circle" alt="User Image">
          </div>
          <div class="pull-left info">
            <p><?=$valores['user']['nome']; ?></p>
          </div>
        </div>

        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
          <li class="header">MENU</li>
 
          <?php if(in_array("PrestacaoContas",$valores['user']['permissao'])){?>      <li><a href="/" onClick='Envio_Ajax("POST", "body_resposta", "load_div", "Home", "exibir","opc=prestacaoContas&act=listar&desc=Prestação de Contas"); return false;'><i class="fa fa-book"></i> <span>Prestação de Contas</span></a></li>                  <?php }?>
          <?php if(in_array("PrevisaoDespesas",$valores['user']['permissao'])){?>     <li><a href="/" onClick='Envio_Ajax("POST", "body_resposta", "load_div", "Home", "exibir","opc=previsaoDespesas&act=listar&desc=Previsão de Despesas"); return false;'><i class="fa fa-file-powerpoint-o"></i> <span>Previsão de Despesas</span></a></li>  <?php }?>          
          <?php if(in_array("TaxaCondominio",$valores['user']['permissao'])){?>       <li><a href="/" onClick='Envio_Ajax("POST", "body_resposta", "load_div", "Home", "exibir","opc=taxaCondominio&act=listar&desc=Taxa de Condomínio"); return false;'><i class="fa fa-barcode"></i> <span>Taxa de Condomínio</span></a></li>                  <?php }?>
          <?php if(in_array("ControleAdimplencia",$valores['user']['permissao'])){?>  <li><a href="/" onClick='Envio_Ajax("POST", "body_resposta", "load_div", "Home", "exibir","opc=controleAdimplencia&act=listar&desc=Controle de Adimplência"); return false;'><i class="fa fa-money"></i> <span>Controle de Adimplência</span></a></li>     <?php }?>

          <li class="header">Extras</li>
          
          <?php if(in_array("Condominio",$valores['user']['permissao'])){?><li><a href="/" onClick='Envio_Ajax("POST", "body_resposta", "load_div", "Home", "exibir","opc=condominios&act=listar&desc=Condomínio"); return false;'><i class="fa fa-building-o"></i> Condomínio</a></li>  <?php }?>         
          <?php if(in_array("Categoria",$valores['user']['permissao'])){?><li><a href="/" onClick='Envio_Ajax("POST", "body_resposta", "load_div", "Home", "exibir","opc=categoria&act=listar&desc=Categoria"); return false;'><i class="fa fa-folder-open-o"></i> Categoria</a></li> <?php }?>
          <?php if(in_array("Usuarios",$valores['user']['permissao'])){?> <li><a href="/" onClick='Envio_Ajax("POST", "body_resposta", "load_div", "Home", "exibir","opc=usuarios&act=listar&desc=Usuários"); return false;'><i class="fa fa-users"></i> <span>Usuários</span></a></li> <?php }?>
          
        </ul>
      </section>
      <!-- /.sidebar -->
    </aside>

    <!-- Div resposta modal-->            
    <div id="modal_resposta"></div> 

    <!-- Div resposta corpo página -->            
    <div class="content-wrapper" id="body_resposta"></div>
    <div id="load_div"></div>
    

    <!-- /.content-wrapper -->
    <footer class="main-footer">
      <div class="pull-right hidden-xs">
        <b>Versão</b> 1.0.0
      </div>
      <strong>Copyright &copy; 2018 <a target="_blank" href="https://jonassuncao.github.io/">@Jônathas Assunção</a> | <a target="_blank" href="https://dominicrp.github.io/">@Dominic Rocha</a> | <a target="_blank" href="https://davidbarros.github.io/">@David
          Antônio</a> | <a target="_blank" href="https://jaderhfa.github.io/">@Jader Henrique</a>.</strong> All rights
      reserved.
    </footer>


  </div>
  <!-- ./wrapper -->
  <!-- jQuery 3 -->
  <script src="Views/Sistema/admin/bower_components/jquery/dist/jquery.min.js"></script>  
  <!-- jQuery UI 1.11.4 -->
  <script src="Views/Sistema/admin/bower_components/jquery-ui/jquery-ui.min.js"></script>
  
  <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
  <script>
   // $.widget.bridge('uibutton', $.ui.button);
  </script>
  <!-- Bootstrap 3.3.7 -->
  <script src="Views/Sistema/admin/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
  <!--Bootstrap-Combobox-->
  <script src ="Views/Sistema/admin/bower_components/bootstrap-combobox/js/bootstrap-combobox.js"></script>
  <!-- Morris.js charts -->
  <script src="Views/Sistema/admin/bower_components/raphael/raphael.min.js"></script>
  <script src="Views/Sistema/admin/bower_components/morris.js/morris.min.js"></script>
  <!-- Sparkline -->
  <script src="Views/Sistema/admin/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
  <!-- jvectormap -->
  <script src="Views/Sistema/admin/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
  <script src="Views/Sistema/admin/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
  <!-- jQuery Knob Chart -->
  <script src="Views/Sistema/admin/bower_components/jquery-knob/dist/jquery.knob.min.js"></script>
  <!-- daterangepicker -->
  <script src="Views/Sistema/admin/bower_components/moment/min/moment.min.js"></script>
  <script src="Views/Sistema/admin/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
  <!-- datepicker -->
  <script src="Views/Sistema/admin/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
  <script src ="Views/Sistema/admin/bower_components/bootstrap-datepicker/dist/locales/bootstrap-datepicker.pt-BR.min.js"></script>
  <!-- Bootstrap WYSIHTML5 -->
  <script src="Views/Sistema/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
  <!-- Slimscroll -->
  <script src="Views/Sistema/admin/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
  <!-- FastClick -->
  <script src="Views/Sistema/admin/bower_components/fastclick/lib/fastclick.js"></script>
  <!-- AdminLTE App -->
  <script src="Views/Sistema/admin/dist/js/adminlte.min.js"></script>
  <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
  <script src="Views/Sistema/admin/dist/js/pages/dashboard.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="Views/Sistema/admin/dist/js/demo.js"></script>
  <!-- iCheck 1.0.1 -->
  <script src="Views/Sistema/admin/plugins/iCheck/icheck.min.js"></script>
  <!--InputMask-->
  <script  src = "Cazulo/Views/Sistema/admin/bower_components/inputmask/dist/jquery.inputmask.bundle.js"></script>


  <script src="Views/js/global_js.js"></script>
  <script src="Views/Sistema/admin/js/login_js.js"></script>
  <script src="Views/Sistema/admin/js/script_js.js"></script>
  
  <!--===============================================================================================-->  
  
</body>

</html>