<?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();       
?>
<section class="content-header">
  <h1>
    <?= $valores['nome']?>    
  </h1>
</section>

<!-- Main content -->
<hr />
<section class="content container-fluid">

  <!--------------------------
        | Your Page Content Here |
        -------------------------->

  <div id="main" class="container-fluid">


    <!--Adcionar botoes-->
    <form>
      <!-- area de campos do form -->

      <!--Adcionar campos-->

      <div class="row">

        <div class="form-group col-md-12">
          <label for="campo1">Razão Social</label>
          <p> <?= $valores['nome']?> </p>

        </div>

        <div class="form-group col-md-3">
          <label for="input-CNPJ">CNPJ</label>
          <p> <?= $valores['cnpj']?> </p>
        </div>

        <div class="form-group col-md-3">
          <label for="campo1">Telefone</label>
          <p> <?= $valores['telefone']?> </p>
        </div>

        <div class="form-group col-md-3">
          <label for="campo1">Celular</label>
          <p> <?= $valores['celular']?> </p>
        </div>

        <div class="form-group col-md-3">
          <label for="exampleInputEmail1">Email</label>
          <p> <?= $valores['email']?> </p>
        </div>


        <div class="form-group col-md-3">
          <label for="campo2">CEP</label>
          <p> <?= $valores['cep']?> </p>
        </div>

        <div class="form-group col-md-3">
          <label for="inputState">Rua</label>
          <p> <?= $valores['rua']?> </p>
        </div>

        <div class="form-group col-md-3">
          <label for="inputState">Numero</label>
          <p> <?= $valores['numero']?> </p>
        </div>

        <div class="form-group col-md-3">
          <label for="inputState">Setor</label>
          <p> <?= $valores['setor']?> </p>
        </div>

        <div class="form-group col-md-6">
          <label for="inputState">Complemento</label>
          <p> <?= $valores['complemento']?> </p>
        </div>

        <div class="form-group col-md-3">
          <label for="inputState">Município</label>
          <p> <?= $valores['municipio']?> </p>
        </div>

        <div class="form-group col-md-2">
          <label for="inputState">Estado</label>
          <p> <?= $valores['estado']?> </p>
        </div>

      </div>
      <hr/>

      <div class="table-wrapper-scroll-y">

        <table class="table table-wrapper-scroll-y">
          <thead>
            <tr>
              <th scope="col">Bancos Castrados</th>
              <th scope="col">Agencia</th>
              <th scope="col">Conta</th>
              <th scope="col">Operação</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <?php foreach ($valores['banco']) { ?>    
              <td><p> <?= $valores['nomeBanco']?> </p></td>
              <td><p> <?= $valores['agencia']?> </p></td>
              <td><p> <?= $valores['conta']?> </p></td>
              <td><p> <?= $valores['operacao']?> </p></td>
              <?php }?> 
            </tr>
          </tbody>
        </table>

      </div>

      <hr />
      <div id="actions" class="row">
        <div class="col-md-12">
          <a href="/" onClick='requisitarServidor("index.php", "Condominios.editar", "route=atualizar&cond="+$("#selectCond").val(), "body_resposta"); return false;' class="btn btn-primary">Atualizar</a>
          <a href="/" onClick='requisitarServidor("index.php", "Condominios.excluir", "cond="+$("#selectCond").val(), "modal_resposta"); return false;' class="btn btn-danger">Excluir</a>
        </div>
      </div>
      <hr />


      <div id="box">
          <div class="form-group col-md-12">
            <p><b>Unidades</b> (Apartamentos)</p>
            <div style="width: 30vw;" class="input-group input-group-sm">
              <input type="text" class="form-control" placeholder="Informe o Apartamento/Torre/Nome Condômino">
              <span class="input-group-btn">
                <button type="button" style="border-radius: 0 4px 4px 0;" class="btn btn-success btn-flat"><i class="fa fa-filter"></i></button>
              </span>
              <a href="/" data-dismiss="modal" style="width: 40px; float:left; margin-left:10px; padding: 4px;" onClick='requisitarServidor("index.php", "Condominos.condomino", "titulo=Adicionar Condômino", "body_resposta"); return false;' class="btn btn-info"><i class="fa fa-plus"></i></a>               
            </div>
  
            <hr />
  
            <select multiple class="form-control" id="exampleFormControlSelect2">
              <option selected>101-B | José da Silva</option>
              <option>102-B | Maria Aparecida</option>
            </select>
  
            <hr />
  
            <div id="actions" class="row">
              <div class="col-md-12">
                <a href="/" onClick='requisitarServidor("index.php", "Condominos.listar", "titulo=Condôminos", "body_resposta"); return false;' class="btn btn-primary">Listar</a>
              </div>
            </div>
  
          </div>
          <div style="clear: both;"></div>
        </div>
      </div>


    </form>



  </div>


</section>