<section class="content-header">
  <h1>
    Jader Henrique Faria Amorim
    <small> - Última Atualização: 16/10/2018 16:55 - ADMIN</small>
  </h1>
</section>
<hr />
<!-- Main content -->
<section class="content container-fluid">

  <!--------------------------
        | Your Page Content Here |
        -------------------------->

  <div id="main" class="container-fluid">


    <!--Adcionar botoes-->
    <form action="index.html">
      <!-- area de campos do form -->

      <!--Adcionar campos-->
      <div class="row">

        <!-- Linha 1 -->
        <div class="form-group col-md-3">
          <label for="campo2">CPF/CNPJ</label>
          <p>000.000/000-00</p>
        </div>

        <div class="form-group col-md-3">
          <label for="campo2">RG/IE</label>
          <p>123456 SSP/GO</p>
        </div>

        <div class="form-group col-md-11">
          <label for="campo1">Nome/Razão Social</label>
          <p>João da Silva</p>
        </div>

        <div class="form-group col-md-3">
          <label for="campo1">Telefone</label>
          <p>(62)3278-6054</p>
        </div>

        <div class="form-group col-md-4">
          <label for="campo1">Celular</label>
          <p>(62) 9 8553-3554</p>
        </div>


        <div class="form-group col-md-4">
          <label for="exampleInputEmail1">Email</label>
          <p>jaderhfa@hotmail.com</p>
        </div>
        <!-- fim linha 2 -->

        <!-- linha 3 -->
        <div class="form-group col-md-3">
          <label for="input-NAp">Apartamento</label>
          <p>1235</p>
        </div>


        <div class="form-group col-md-4">
          <label for="input-NTorre">Torre</label>
          <p>B</p>
        </div>

        <div class="form-group col-md-5">
          <label for="inputState">Endereço</label>
          <p>Condominio Liberty II (00.000.000/0000-00)</p>
        </div>

      </div>

      <hr />

      <div class="table-wrapper-scroll-y">

        <table class="table table-wrapper-scroll-y">
          <thead>
            <tr>
              <th scope="col">Descrição</th>
              <th scope="col">Valor</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Taxa de Mudança</td>
              <td>R$ 250,00</td>
            </tr>
            <tr>
              <td>Garagem - <b>(Mensal)</b></td>
              <td> 6.0%</td>
            </tr>
            <tr>
              <td>Isenção - <b>(Mensal)</b></td>
              <td> - 100.0%</td>
            </tr>
          </tbody>
        </table>

      </div>

      <hr />

      <div id="actions" class="row">
        <div class="col-md-12">
          <a href="" class="btn btn-default">Voltar</a>
          <a href="" class="btn btn-primary">Atualizar</a>
        </div>
      </div>

      <hr />


  </div>

  </form>

  </div>

</section>