<?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();    
?>
<div class="modal modal-warning fade" id="modal-warning" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span></button>
        <h4 class="modal-title"><?= $valores['header']?></h4>
      </div>
      <div class="modal-body">
        <p><?= $valores['body']?></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline" data-dismiss="modal">Fechar</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<script>
  $('#modal-warning').modal();
</script>