<?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();       
?>
<div class="modal modal-warning fade" id="modal-warning" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span></button>
        <h4 class="modal-title"><?= $valores['header']?></h4>
      </div>
      <div class="modal-body">
        <p><?= $valores['body']?></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline" data-dismiss="modal">Fechar</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<script type="text/javascript">
//Exibir o modal

/**
 * Essa função carrega um <script> dinamicamente
 * @param url --> URL do .js
 * @param callback --> função do que fazer quando finalizar
 */
function loadScript(url, callback){
  
  const body = document.getElementsByTagName('body')[0];   
  let script = document.createElement("script");

  script.src = url;
  script.type = "text/javascript";

   script.onreadystatechange = callback;
   script.onload = callback;
   
   body.appendChild(script);
}


  //Tenta exibir o modal
  try {    
    $('#modal-danger').modal();
  }catch (e) { //Caso não consiga exibir o modal, importa as bibliotecas do modal e tenta novamente

    //Importa os CSS
    const styles = [
      "Views/Sistema/Admin/dist/css/AdminLTE.min.css",
      "Views/Sistema/Admin/bower_components/bootstrap/dist/css/bootstrap.min.css"      
    ];

    // Objetos de manipulação do DOM:
    const head = document.getElementsByTagName('head')[0];

    // Insere os arquivos CSS na página:
    for (let i in styles) {
      let style = document.createElement("link");

      style.rel = 'stylesheet';
      style.type = 'text/css';
      style.href = styles[i];

      head.appendChild(style);
    }

    let style = document.createElement("link");

    style.rel = 'icon';
    style.type = 'image/ico';
    style.href = "Views/Sistema/Admin/images/icons/favicon.ico";

    head.appendChild(style);
    //Fim Importa CSS

    //Importa os js e exibe o modal
    const scripts = [
      "Views/Sistema/Admin/bower_components/jquery/dist/jquery.min.js",
      "Views/Sistema/Admin/bower_components/bootstrap/dist/js/bootstrap.min.js"
    ];
    
    var boot = function(){
      loadScript(scripts[1], function(){$('#modal-danger').modal();});
    };

    loadScript(scripts[0], boot);
    //Fim Importa os js e exibe o modal
 } 
</script>