<?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();       
?>
<div class="modal modal-danger fade" id="modal-danger" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span></button>
        <h4 class="modal-title"><?= $valores['header']?></h4>
      </div>
      <div class="modal-body">
        <p style="color: black" ><?= $valores['body']?></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline" data-dismiss="modal">Fechar</button>        
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

<link rel="stylesheet" href="Views/Sistema/admin/bower_components/bootstrap/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="Views/Sistema/admin/dist/css/AdminLTE.min.css">  

<script src="Views/Sistema/admin/bower_components/jquery/dist/jquery.min.js"></script>    
<script src="Views/Sistema/admin/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script>
  $('#modal-danger').modal();
</script>