<?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();  
    $header = $valores['header'];     
?>

<section id="new">
  <div>
    <h5>Banco: <img style="width: 20px;" src="Views/Sistema/admin/images/<?= $header['Banco-img']?>.png" alt="img-Banco"> 
      <b><?= $header['Banco']?></b></h5>
      <h5>Cliente: <b><?= var_dump($header)?></b></h5>
      <h5>Conta:   <b><?= $header['Cliente']?></b></h5>
      <h5>Data:    <b><?= $header['Data']?></b></h5>
      <h5>Período: <b><?= $header['Periodo']?></b></h5>
  </div>

  <!-- Inicio Importar arquivo Extrato -->
  <form id="salvarDoc" enctype="multipart/form-data">
    <input type="hidden" name="controller" value="Home" />
    <input type="hidden" name="action" value="exibir" />
    <input type="hidden" name="opc" value="prestacaoContas" />
    <input type="hidden" name="desc" value="Prestacao de Contas" />
    <input type="hidden" name="act" value="listarEXT" />
    <input type="hidden" name="banco" value="bb" />
    <input type="hidden" name="ag" value="1234" />
    <input type="hidden" name="op" value="003" />
    <input type="hidden" name="conta" value="12345678-9" />

    <div class="form-group">
      <div class="input-group input-file" name="Fichier1">
        <span class="input-group-btn">
              <button class="btn btn-info btn-choose" type="button"><i class="fa fa-fw fa-cloud-upload"></i> Selecionar
      Arquivo</button>
        </span>
        <input type="text" class="form-control" placeholder='Selecionar arquivo...' />
        <span class="input-group-btn">
              <button class="btn btn-success"  id="enviaArq" type="button"><i class="fa fa-fw fa-flash "></i></button>
        </span>  
      </div>
    </div>
  </form>
	<!-- FIM Importar arquivo Extrato -->

  <table class="table table-striped">
    <tr>
      <th>Data</th>
      <th>Num. Doc.</th>
      <th>Descrição</th>
      <th>Valor</th>
      <th>Saldo</th>
      <th style="width: 10px"></th>
    </tr>
    <tr>
      <td style="font-weight: bold;">01/09/2017</td>
      <td></td>
      <td style="font-weight: bold;">SALDO ANTERIOR</td>
      <td>=====</td>
      <td style="font-weight: bold;">R$ 15.151,95</td>
      <td></td>
    </tr>
    <tr>
      <td>04/09/2017</td>
      <td>291712</td>
      <td>PAG BOLETO</td>
      <td style="color: red">- 7.143,14</td>
      <td>8.008,81</td>
      <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
    </tr>
    <tr>
      <td>08/09/2017</td>
      <td>040817</td>
      <td>COB LOT DH</td>
      <td style="color: green">+ 1.428,09</td>
      <td>9.436,90</td>
      <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
    </tr>
    <tr>
      <td>10/09/2017</td>
      <td>097301</td>
      <td>ENVIO TEV</td>
      <td style="color: red">- 3.375,41</td>
      <td>6.061,49</td>
      <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
    </tr>
    <tr>
      <td>15/09/2017</td>
      <td>902108</td>
      <td>CHEQUE SAC</td>
      <td style="color: red">- 2.365,23</td>
      <td>3.696,26</td>
      <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
    </tr>
    <tr>
      <td style="font-weight: bold;">30/09/2017</td>
      <td></td>
      <td style="font-weight: bold;">SALDO FINAL</td>
      <td>=====</td>
      <td style="font-weight: bold;">R$ 3.696,26</td>
      <td></td>
    </tr>
  </table>
</section>

<script>
function bs_input_file() {
	$(".input-file").before(
		function() {
			if ( ! $(this).prev().hasClass('input-ghost') ) {
				var element = $("<input type='file' accept='.txt' id='inp_extrato' nome='ext' class='input-ghost' style='visibility:hidden; height:0'>");
				element.attr("name",$(this).attr("name"));
				element.change(function(){
					element.next(element).find('input').val((element.val()).split('\\').pop());
				});
				$(this).find("button.btn-choose").click(function(){
					element.click();
				});
				$(this).find('input').css("cursor","pointer");
				$(this).find('input').mousedown(function() {
					$(this).parents('.input-file').prev().click();
					return false;
				});
				return element;
			}
		}
	);
}

$(function() {
	bs_input_file();
});  

$('#enviaArq').click(function () {
    var form = new FormData(salvarDoc);
    form.append('ext', $('#inp_extrato').get(0).files[0]); // para apenas 1 arquivo
    Envio_Ajax('POST', 'banco', '', '', '', form);
});

</script>