<!--?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();       
?-->
<section class="content-header">
  <h1>
    Prestação de Contas
  </h1>
</section>

<section class="content">    
  <div class="row">

    <!-- Início Período-->
    <div class="col-xs-4" style="min-width: 400px;">
      <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="box-title">Período</h3>                      
        </div>

        <div class="box-body">
          <div class="col-md-16">

          <!-- Início Ano-->
            <div class="form-group" style="width: 100px; float:left; margin-right:10px;">
              <label>Ano</label>
              <select class="form-control select2">
                <option selected="selected">2018</option>
                <option>2017</option>
                <option>2016</option>
                <option>2015</option>
              </select>
            </div>
           <!-- Fim Ano--> 
           <!-- Início Mês-->
            <div class="form-group" style="width: 100px; float:left;">
              <label>Mês</label>
              <select class="form-control select2">
                <option selected="selected">12</option>
                <option>11</option>
                <option>10</option>
                <option>09</option>
                <option>08</option>
                <option>07</option>
                <option>06</option>
                <option>05</option>
                <option>04</option>
                <option>03</option>
                <option>02</option>
                <option>01</option>
              </select>
            </div>
            <!-- Fim Mês-->
            <!-- Início Botões-->
            <div class="row" style="width: 40px; float:left; margin-left:10px;">
              <button type="button" title="Iniciar Nova Prestação" class="btn btn-block btn-success"><i class="fa fa-plus"></i></button>
              <button type="button" title="Buscar Taxa de Condomínio" class="btn btn-block btn-info"><i class="fa fa-search"></i></button>
            </div>
            <div class="row" style="width: 40px; float:left; margin-left:25px;">
              <button type="button" title="Fechar Prestação" class="btn btn-block btn-primary"><i class="fa fa-lock"></i></button>              
              <button type="button" title="Imprimir Prestação" class="btn btn-block btn-primary"><i class="fa fa-print"></i></button>              
            </div>            
            <!-- Fim Botões-->

          </div>
        </div>
      </div>
    </div>
    <!-- Fim Período-->

   <!-- Início Prestação/Extrato-->
   <div class="col-xs-12">
      <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#resumo"      data-toggle="tab">Prestação de Contas</a></li>
          <li class="">      <a href="#documentos"  data-toggle="tab">Documentos</a></li>
          <li class="">      <a href="#extrato"     data-toggle="tab">Extrato</a></li>
          <li class="">      <a href="#despesas"    data-toggle="tab">Reconhecimento das Despesas de Exercícios Futuros</a></li>
          <li class="">      <a href="#carteira"    data-toggle="tab">Reconhecimento das Receitas de Exercícios Futuros</a></li>
        </ul>
      
        <!-- Início conteúdo-->
        <div class="tab-content">

          <!-- Início conteúdo Prestação-->
          <div class="tab-pane active" id="resumo">
            <section id="new">
                          
              <!-- Início Tabela Receita-->
              <div style="width:100%;">
                <div class="div_table_receita div_table">
                  <div class="box-header"><h3 class="box-title"><b>Receitas</b></h3></div>            
                  <div class="box-body no-padding">
                    <table class="table table-striped">
                    <tr>
                        <td>Saldo Transportado</td>
                        <td>10.000,00</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>  
                      <tr>
                        <td>Taxas de Condominio</td>
                        <td>33.754,16</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>
                      <tr>
                        <td>Juros sobre Taxas de Condominio</td>
                        <td>320,84</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                         
                      <tr>
                        <td>Reconhecimento das Receitas de Exercícios Futuros</td>
                        <td>4.095,84</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                                      
                      <tr>
                        <td>Juros Bancários</td>
                        <td>55,25</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>               
                      <tr>
                        <td>Recebimento de Acordos</td>
                        <td>38.873,17</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>             
                      <tr>
                        <td>TOTAL</td>
                        <td>R$ <b>87.099,26</b></td>                        
                        <td></td>
                      </tr>                  
                    </table>                                        
                  </div>                
                </div>                                      
                <div style="clear: both;"></div>
              </div> 
              <!-- Fim Tabela Receita-->

              <!-- Início Tabela Administrativas/Diversos-->
              <div style="width:100%;">
                <!-- Início Tabela Despesas Administrativas-->
                <div class="div_table_despesas div_table">
                  <div class="box-header"><h3 class="box-title"><b>Despesas - Administrativas</b></h3></div>            
                  <div class="box-body no-padding">
                    <table class="table table-striped">
                      <tr>
                        <td>Honorário Contábeis</td>
                        <td>1.836,52</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>    
                      <tr>
                        <td>Pro-Lábore Síndico</td>
                        <td>2.500,00</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                                   
                      <tr>
                        <td>Celg</td>
                        <td>1.211,34</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>               
                      <tr>
                        <td>TOTAL</td>
                        <td>R$ <b>5.547,86</b></td>                       
                        <td></td>
                      </tr>                                                    
                    </table>                                        
                  </div>
                </div>
                <!-- Fim Tabela Despesas Administrativas-->

                <!-- Início Tabela Despesas Diversas-->
                <div class="div_table_despesas div_table">
                  <div class="box-header"><h3 class="box-title"><b>Despesas - Diversas</b></h3></div>            
                  <div class="box-body no-padding">
                    <table class="table table-striped">   
                      <tr>
                        <td>Descontos sobre Taxas de Condominio</td>
                        <td>20,84</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                         
                      <tr>
                        <td>Reconhecimento das Despesas de Exercicios Futuros</td>
                        <td>9.562,51</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                            
                      <tr>
                        <td>Materiais de Limpeza</td>
                        <td>2.365,23</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>
                      <tr>
                        <td>Equipamentos de Informática</td>
                        <td>2.092,78</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                                                              
                      <tr>
                        <td>TOTAL</td>
                        <td>R$ <b>14.041,36</b></td>
                        <td></td>
                      </tr>                                                    
                    </table>                                        
                  </div>
                </div>
                <!-- Fim Tabela Despesas Diversas-->
                
                <div style="clear: both;"></div>
              </div> 
              <!-- Fim Despesas Administrativas/Diversos-->

              <!-- Início Tabela Despesas EncargosSociais/Bancarios-->
              <div style="width:100%;">
                <!-- Início Tabela Despesas - Encargos Sociais-->
                <div class="div_table_despesas div_table">
                  <div class="box-header"><h3 class="box-title"><b>Despesas - Encargos Sociais</b></h3></div>            
                  <div class="box-body no-padding">
                    <table class="table table-striped">
                      <tr>
                        <td>FGTS</td>
                        <td>1.134,92</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                         
                      <tr>
                        <td>TOTAL</td>
                        <td>R$ <b>1.134,92</b></td>
                        <td></td>
                      </tr>                                                    
                    </table>                                        
                  </div>
                </div>
                <!-- Fim Tabela Despesas - Encargos Sociais-->

                <!-- Início Tabela Despesas Bancáriais-->
                <div class="div_table_despesas div_table">
                  <div class="box-header"><h3 class="box-title"><b>Despesas - Bancárias</b></h3></div>            
                  <div class="box-body no-padding">
                    <table class="table table-striped">
                      <tr>
                        <td>Tarifa Bancária</td>
                        <td>1.416,80</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                         
                      <tr>
                        <td>TOTAL</td>
                        <td>R$ <b>1.416,80</b></td>
                        <td></td>
                      </tr>                                                    
                    </table>                                                      
                  </div>
                </div>
                <!-- Fim Tabela Despesas Bancárias-->
                
                <div style="clear: both;"></div>
              </div> 
              <!-- Fim Despesas EncargosSociais/Bancarios-->

              <!-- Inicio Saldo a Transportar-->
              <div style="width:100%">
                <div class="div_table_result">
                  <div class="box-body no-padding">
                  <table class="table table-striped">
                    <tr>
                      <td>Receitas</td>
                      <td style="color: green;"><b>+ 87.099,26</b></td>
                      <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                    </tr>               
                    <tr>
                      <td>Despesas</td>
                      <td style="color: red;"><b>- 22.140,94</b></td>
                      <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                    </tr>               
                    <tr>
                      <td>Saldo a Transportar</td>
                      <td style="color: green;">R$ <b>64.958,32</b></td>
                      <td></td>
                    </tr>                                                    
                  </table>                                        
                  </div>                
                </div>                                      
                <div style="clear: both;"></div>
              </div>                                                   
              <!-- Fim Saldo a Transportar-->              
              
              <hr>

              <div style="width:100%;">
                <!-- Início Tabela Informe Adminsitrativo-->
                <div class="div_table_result div_table_bancario div_table">
                  <div class="box-header"><h3 class="box-title"><b>Saldo Bancário - 30/09/2017</b></h3></div>            
                  <div class="box-body no-padding">
                    <table class="table table-striped">
                      <tr>
                        <td>Saldo Conta Corrente | 1234 / 003 / 12345678-9</td>
                        <td>3.696,26</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>         
                      <tr>
                        <td>Saldo Conta Poupança | 1234 / 013 / 12345678-9</td>
                        <td>39.717,38</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                                               
                      <tr>
                        <td>TOTAL</td>
                        <td>R$ <b>43.413,64</b></td>
                        <td></td>
                      </tr>                                                    
                    </table>                                        
                  </div>
                </div>
                <!-- Fim Tabela Informe Administrativo-->
                <div style="clear: both;"></div>
              </div>

              <!-- Início Tabela Demostrativos a Receber/Pagar-->
              <div style="width:100%;">
                <!-- Início Tabela Receitas de Exercícios Futuros-->
                <div class="div_table_receita div_table">
                  <div class="box-header"><h3 class="box-title"><b>Reconhecimento das Receitas de Exercícios Futuros</b></h3></div>            
                  <div class="box-body no-padding">
                    <table class="table table-striped">
                      <tr>
                        <td>Recebimento de Acordo (1014B072018)</td>
                        <td>1.463,87</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>         
                      <tr>
                        <td>Recebimento de Acordo (1044B072018)</td>
                        <td>2.365,23</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>         
                      <tr>
                        <td>Taxa de Condominio (3062EB062018)</td>
                        <td>266,74</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                                                                                         
                      <tr>
                        <td>TOTAL</td>
                        <td>R$ <b>4.095,84</b></td>
                        <td></td>
                      </tr>                                                    
                    </table>                                        
                  </div>
                </div>   
                <!-- Fim Tabela Receitas de Exercícios Futuros-->

                <!-- Início Tabela Despesas de Exercicios Futuros-->
                <div class="div_table_despesas div_table">
                  <div class="box-header"><h3 class="box-title"><b>Reconhecimento das Despesas de Exercicios Futuros</b></h3></div>            
                  <div class="box-body no-padding">
                    <table class="table table-striped">
                      <tr>
                        <td>Cheque (902109) - MB Vidros</td>
                        <td>1.463,87</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>       
                      <tr>
                        <td>Cheques (902110) - Parcela 1/4 - NF:12345-2 - DELL Computadores</td>
                        <td>2.024,66</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>         
                      <tr>
                        <td>Cheques (902111) - Parcela 2/4 - NF:12345-2 - DELL Computadores</td>
                        <td>2.024,66</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>         
                      <tr>
                        <td>Cheques (902112) - Parcela 3/4 - NF:12345-2 - DELL Computadores</td>
                        <td>2.024,66</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>         
                      <tr>
                        <td>Cheques (902113) - Parcela 4/4 - NF:12345-2 - DELL Computadores</td>
                        <td>2.024,66</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                                                                                                                                       
                      <tr>
                        <td>TOTAL</td>
                        <td>R$ <b>9.562,51</b></td>
                        <td></td>
                      </tr>                                                    
                    </table>                                        
                  </div>
                </div>                
                <!-- Fim Tabela Despesas a Pagar-->              
                <div style="clear: both;"></div>
              </div> 
              <!-- Fim Tabela Demostrativos a Receber/Pagar-->

              <!-- Início Tabela Demostrativos a Receber/Pagar Realizados-->
              <div style="width:100%;">
                <!-- Início Tabela Informe Adminsitrativo-->
                <div class="div_table_receita div_table">
                  <div class="box-header"><h3 class="box-title"><b>Compensação das Receitas de Exercicios Passados</b></h3></div>            
                  <div class="box-body no-padding">
                    <table class="table table-striped">               
                      <tr>
                        <td>Taxa de Condominio (3062EB092018)</td>
                        <td>372,74</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                                                                                         
                      <tr>
                        <td>TOTAL</td>
                        <td>R$ <b>372,74</b></td>
                        <td></td>
                      </tr>                                                    
                    </table>                                        
                  </div>
                </div>   
                <!-- Fim Tabela Informe Administrativo-->

                <!-- Início Tabela Despesas a Compensar-->
                <div class="div_table_despesas div_table">
                  <div class="box-header"><h3 class="box-title"><b>Compensação das Despesas de Exercicios Passados</b></h3></div>            
                  <div class="box-body no-padding">
                    <table class="table table-striped">
                      <tr>
                        <td>Cheque (902234) - Jardinagem</td>
                        <td>463,87</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr> 
                      <tr>
                        <td>Cheques (902108) - NF:1235645-2 - Gás</td>
                        <td>2.371,09</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                                                                     
                      <tr>
                        <td>TOTAL</td>
                        <td>R$ <b>2.834,96</b></td>
                        <td></td>
                      </tr>                                                    
                    </table>                                        
                  </div>
                </div>                
                <!-- Fim Tabela Despesas a Compensar-->              
                <div style="clear: both;"></div>
              </div> 
              <!-- Fim Demostrativos a Receber/Pagar Realizados-->

              <!-- Início Tabela Demonstrativo Saldo-->
              <div style="width:100%">
                <div class="div_table_result">
                  <div class="box-body no-padding">
                  <table class="table table-striped">
                    <tr>
                      <td>Saldo Bancário</td>
                      <td style="color: green;">+ 43.413,64</td>
                      <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                    </tr>  
                    <tr>
                      <td>Reconhecimento das Receitas de Exercicios Futuros</td>
                      <td style="color: green;">+ 4.095,84</td>
                      <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                    </tr>     
                    <tr>
                      <td>Compensação das Receitas de Exercicios Passados</td>
                      <td style="color: red;">- 372,74</td>
                      <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                    </tr>                                                   
                    <tr>
                      <td>Reconhecimento das Despesas de Exercicios Futuros</td>
                      <td style="color: red;">- 9.562,51</td>
                      <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                    </tr>            
                    <tr>
                      <td>Compensação das Despesas de Exercicios Passados</td>
                      <td style="color: green;">+2.834,96</td>
                      <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                    </tr>                        
                    <tr>
                      <td>Caixa</td>
                      <td style="color: green;">+ 24.549,13</td>
                      <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                    </tr>                                   
                    <tr>
                      <td>Saldo a Transportar em <b>30/09/2017</b></td>
                      <td style="color: green;">R$ <b>64.958,32</b></td>
                      <td></td>
                    </tr>                                                    
                  </table>                                        
                  </div>                
                </div>                                      
                <div style="clear: both;"></div>
              </div>                                                                 
              <!-- Fim Tabela Demonstrativo Saldo-->
                
            </section>
          </div>
          <!-- Fim conteúdo Prestação-->

          <!-- Inicio Documentos-->
          <div class="tab-pane" id="documentos">
            <section id="new">                 
              <button type="button" title="Iniciar Nova Prestação" data-toggle="modal" data-target="#myAddDoc" class="btn btn-block btn-success"><i class="fa fa-plus"></i></button>              
              <!-- Modal -->
              <div class="modal fade" id="myAddDoc" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <!--Botão para fechar tela Modal-->
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <h4 class="modal-title" id="myModalLabel">Adicionar Documento</h4>
                    </div><!--/.modal-header-->
                    <div class="modal-body" style="background-color: #ecf0f5; padding: 10px">
                      <form>
                        <!-- Inicio Form Documento-->
                        <div class="box box-default">
                          <div class="box-header with-border">
                            <h3 class="box-title">Documento Fiscal</h3>                      
                          </div>
                  
                          <div class="box-body">
                            <div class="col-md-16">
                  
                              <!-- Início Tipo-->
                              <div class="form-group" style="width: 110px; float:left; margin-right:10px;">
                                <label>Grupo</label>
                                <select class="form-control select2">
                                  <option>Receitas</option>
                                  <option selected="selected">Despesas</option>
                                </select>
                              </div>
                              <!-- Fim Tipo--> 

                              <!-- Início Conta-->
                              <div class="form-group" style="width: 280px; float:left; margin-right:10px;">
                                <label>Conta</label>
                                <select class="form-control select2">
                                    <option>Honorário Contábeis</option>
                                    <option>Pro-Lábore Síndico</option>
                                    <option>Energia</option>
                                    <option>Materiais de Limpeza</option>
                                    <option selected="selected">Equipamentos de Informática</option>
                                </select>
                              </div>
                              <!-- Fim Conta-->

                              <!-- Início Tipo-->
                              <div class="form-group" style="width: 150px; float:left;">
                                <label>Tipo</label>
                                <select class="form-control select2">
                                    <option selected="selected">Nota Fiscal</option>
                                    <option>Cupom Fiscal</option>
                                    <option>Contra-Cheque</option>
                                    <option>Imposto</option>
                                </select>
                              </div>
                              <!-- Fim Tipo-->

                              <!-- Início Descrição-->
                              <div class="form-group" style="width: 100%; float:left;">
                                  <div>
                                    <div class="form-group" style="width: 170px; float:left; margin-right:20px;">  
                                      <label for="example-input-1">Data Emissão</label>
                                      <input type="date" class="form-control" id="example-input-1">                            
                                    </div>
                                    <div class="form-group" style="width: 150px; float:left; margin-right:20px;">
                                        <label for="example-input-1">Identificação</label>
                                        <input type="text" class="form-control" id="example-input-1">                                                                                          
                                    </div>                                                                    
                                    <div class="form-group" style="width: 150px; float:left;">
                                        <label for="example-input-1">Valor Total Documento</label>
                                        <input type="number" class="form-control" id="example-input-1">                                    
                                    </div>
                                    <div style="clear: both;"></div> 
                                  </div>  
                                  <div>
                                    <label for="example-input-1">Descrição</label>
                                    <input type="text" class="form-control" id="example-input-1">                                                        
                                  </div>
                              </div>
                              <!-- Fim Descrição-->
                            </div>
                          </div>
                        </div>   
                        <!-- Fim Form Documento-->
                        
                        <!-- Inicio Form Reconhecimento Futuro-->
                        <div class="box box-default">
                            <div class="box-header with-border">
                              <h3 class="box-title">Reconhecer para Exercícios Futuros</h3>                      
                            </div>
                    
                              <table class="table table-striped">
                                  <tr>
                                    <th>Identificação</th>
                                    <th>Descrição</th>
                                    <th>Valor</th>
                                    <th style="width: 10px"></th>
                                  </tr>
                                  <tr>
                                    <td style="width: 10px"><input type="text" class="form-control" id="example-input-1" value="902110"/></td>
                                    <td style="width: 250px"><input type="text" class="form-control" id="example-input-1" value="Parcela 2/5 - DELL Computadores"/></td>
                                    <td style="width: 100px"><input type="text" class="form-control" id="example-input-1" value="2.092,77"/></td>
                                    <td><i class="fa fa-trash"></i> </td>               
                                  </tr> 
                                  <tr>
                                    <td style="width: 10px"><input type="text" class="form-control" id="example-input-1" value="902111"/></td>
                                    <td style="width: 250px"><input type="text" class="form-control" id="example-input-1" value="Parcela 3/5 - DELL Computadores"/></td>
                                    <td style="width: 100px"><input type="text" class="form-control" id="example-input-1" value="2.092,77"/></td>
                                    <td><i class="fa fa-trash"></i> </td>               
                                  </tr>                                                   
                              </table>    
                              <div class="modal-footer">                                  
                                <button type="button" class="btn btn-success"><i class="fa fa-plus"></i></button>
                              </div><!--/.modal-footer-->
                          </div>                           
  
                        <!-- Fim Form Reconhecimento Futuro-->

                        <!-- Inicio Form Extrato-->
                          <div class="box box-default">
                            <div class="box-header with-border">
                              <h3 class="box-title">Identificar no Extrato Bancário</h3>                      
                            </div>
                    
                            <div class="box-body">
                              <div class="col-md-16">                                                      
                                  <input style="width: 150px; float:left; margin-right:20px;" type="number" class="form-control" id="example-input-1" disabled>                                                                                          
                                  <button style="width: 150px; float:left; margin-right:20px;" type="button" title="Localizar lançamento no Extrato" class="btn btn-block btn-info"><i class="fa fa-sync"></i>Buscar</button>                                    
                                  <p> Identificação no Extrato: <b>902114</b></p>                      
                              </div>
                            </div>
                          </div>                           
                        <!-- Fim Form Extrato-->

                        <div style="clear: both;"></div>                                              
                      </form>                        
                    </div><!--/.modal-body-->
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                      <button type="button" class="btn btn-success">Adicionar</button>
                    </div><!--/.modal-footer-->
                  </div><!--/.modal-content-->
                </div><!--/modal-dialog-->
              </div>              
              <table class="table table-striped">
                <tr>
                  <th>Data Emissão</th>
                  <th>Num. Doc.</th>
                  <th>Descrição</th>
                  <th>Valor</th>
                  <th style="width: 10px"></th>
                </tr>
                <tr>
                  <td>07/09/2017</td>
                  <td>12345-2</td>
                  <td>DELL Computadores</td>
                  <td>10.463,87</td>
                  <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                </tr>          
                <tr>
                  <td>10/09/2017</td>
                  <td>1234-56</td>
                  <td>Supermercado ABC</td>
                  <td>2.365,23</td>
                  <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                </tr>  
                <tr>
                  <td>01/09/2017</td>
                  <td>08/2017</td>
                  <td>Pro-lábore - Síndico</td>
                  <td>2.500,00</td>
                  <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                </tr>                                        
                <tr>
                  <td></td>
                  <td></td>
                  <td style="font-weight: bold;">TOTAL</td>                  
                  <td style="font-weight: bold;">R$ 15.329,10</td>                  
                  <td></td>
                </tr>                
              </table>                                                                              
            </section>
          </div>              
          <!-- Fim Documentos-->

          <!-- Início conteúdo Extrato-->
          <div class="tab-pane" id="extrato">
            <section id="new">
            <!-- Início Contas-->  
            <div class="nav-tabs-custom">
              <ul class="nav nav-tabs">
                <li class="active"><a href="#ccCaixa" data-toggle="tab"><img style="width: 20px;" src="Views/Sistema/admin/images/caixa.png" alt="caixa"></span> Conta Corrente<span class="logo-lg"></a></li>
                <li class="">      <a href="#cpBB" data-toggle="tab"><img style="width: 20px;" src="Views/Sistema/admin/images/bb.png" alt="bb"></span> Conta Poupança<span class="logo-lg"></a></li>
              </ul>

              <!-- Início conteúdo Contas-->
              <div class="tab-content">

                <!-- Início conteúdo ContaCorrente-->
                <div class="tab-pane active" id="ccCaixa">
                  <section id="new">
                    <div>
                      <h5>Banco: <img style="width: 20px;" src="Views/Sistema/admin/images/caixa.png" alt="caixa"> <b>Caixa Econômica Federal</b></h6>
                      <h5>Cliente: <b>Condomínio Residencial AAAAAA</b></h5>
                      <h5>Conta: <b>1234 / 003 / 12345678-9</b></h5>
                      <h5>Data: <b>01/10/2017 - 12:03</b></h5>          
                      <h5>Mês: <b>Setembro/2017</b></h5>
                    </div>                    
                    <button type="button" class="btn btn-block btn-info"><i class="fa fa-fw fa-cloud-upload"></i> Importar Extrato</button>
                    <table class="table table-striped">
                      <tr>
                        <th>Data</th>
                        <th>Num. Doc.</th>
                        <th>Descrição</th>
                        <th>Valor</th>
                        <th>Saldo</th>
                        <th style="width: 10px"></th>
                      </tr>
                      <tr>
                        <td style="font-weight: bold;">01/09/2017</td>
                        <td></td>
                        <td style="font-weight: bold;">SALDO ANTERIOR</td>
                        <td>=====</td>
                        <td style="font-weight: bold;">R$ 15.151,95</td>   
                        <td></td>               
                      </tr>
                      <tr>
                        <td>04/09/2017</td>
                        <td>291712</td>
                        <td>PAG BOLETO</td>
                        <td style="color: red">- 7.143,14</td>
                        <td>8.008,81</td>
                        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>
                      <tr>
                        <td>08/09/2017</td>
                        <td>040817</td>
                        <td>COB LOT DH</td>
                        <td style="color: green">+ 1.428,09</td>
                        <td>9.436,90</td>
                        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>
                      <tr>
                        <td>10/09/2017</td>
                        <td>097301</td>
                        <td>ENVIO TEV</td>
                        <td style="color: red">- 3.375,41</td>
                        <td>6.061,49</td>
                        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                       
                      <tr>
                        <td>15/09/2017</td>
                        <td>902108</td>
                        <td>CHEQUE SAC</td>
                        <td style="color: red">- 2.365,23</td>
                        <td>3.696,26</td>
                        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                      
                      <tr>
                        <td style="font-weight: bold;">30/09/2017</td>
                        <td></td>
                        <td style="font-weight: bold;">SALDO FINAL</td>
                        <td>=====</td>
                        <td style="font-weight: bold;">R$ 3.696,26</td>                  
                        <td></td>
                      </tr>                
                    </table>                                        
                  </section>
                </div>
                <!-- Fim conteúdo ContaCorrente-->

                <!-- Início conteúdo ContaPoupanca-->
                <div class="tab-pane" id="cpBB">
                  <section id="new">
                    <div>
                      <h5>Banco: <img style="width: 20px;" src="Views/Sistema/admin/images/bb.png" alt="bb"> <b>Banco do Brasil</b></h6>
                      <h5>Cliente: <b>Condomínio Residencial AAAAAA</b></h5>
                      <h5>Conta: <b>1234 / 013 / 12345678-9</b></h5>
                      <h5>Data: <b>01/10/2017 - 12:10</b></h5>          
                      <h5>Mês: <b>Setembro/2017</b></h5>
                    </div>
                    <button type="button" class="btn btn-block btn-info"><i class="fa fa-fw fa-cloud-upload"></i> Importar Extrato</button>
                    <table class="table table-striped">
                      <tr>
                        <th>Data</th>
                        <th>Num. Doc.</th>
                        <th>Descrição</th>
                        <th>Valor</th>
                        <th>Saldo</th>
                        <th style="width: 10px"></th>
                      </tr>
                      <tr>
                        <td style="font-weight: bold;">01/09/2017</td>
                        <td></td>
                        <td style="font-weight: bold;">SALDO ANTERIOR</td>
                        <td>=====</td>
                        <td style="font-weight: bold;">R$ 20.338,79</td>   
                        <td></td>               
                      </tr>
                      <tr>
                        <td>03/09/2017</td>
                        <td>000000</td>
                        <td>REM BASICA</td>
                        <td style="color: green">+ 3,18</td>
                        <td>20.341,97</td>
                        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>
                      <tr>
                        <td>04/09/2017</td>
                        <td>001550</td>
                        <td>DEB.AUTOR.</td>
                        <td style="color: red">- 16.000,00</td>
                        <td>4.341,97</td>
                        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>    
                      <tr>
                        <td>11/09/2017</td>
                        <td>097301</td>
                        <td>ENVIO TEV</td>
                        <td style="color: green">+ 3.375,41</td>
                        <td>7.717,38</td>
                        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                                          
                      <tr>
                        <td>08/09/2017</td>
                        <td>608000</td>
                        <td>CONV608000</td>
                        <td style="color: green">+ 32.000,00</td>
                        <td>39.717,38</td>
                        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>
                      <tr>
                        <td style="font-weight: bold;">30/09/2017</td>
                        <td></td>
                        <td style="font-weight: bold;">SALDO FINAL</td>
                        <td>=====</td>
                        <td style="font-weight: bold;">R$ 39.717,38</td>                  
                        <td></td>
                      </tr>                
                    </table>                                                                              
                  </section>
                </div>
                <!-- Fim conteúdo ContaPoupanca-->
              </div>
              <!-- Fim conteúdo Contas-->
            </div> 
            <!-- Fim Contas-->  

            </section>
          </div>
          <!-- Fim conteúdo Extrato-->

          <!-- Inicio Despesas a Compensar-->
          <div class="tab-pane" id="despesas">
            <section id="new">              
              <table class="table table-striped">
                <tr>
                  <th>Data</th>
                  <th>Num. Doc.</th>
                  <th>Descrição</th>
                  <th>Valor</th>
                  <th style="width: 10px"></th>
                </tr>
                <tr>
                  <td>03/09/2017</td>
                  <td>902109</td>
                  <td>Cheque - MB Vidros</td>
                  <td>1.463,87</td>
                  <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                </tr>       
                <tr>
                  <td>07/09/2017</td>
                  <td>902110</td>
                  <td>Cheques - Parcela 1/4 - DELL Computadores</td>
                  <td>2.024,66</td>
                  <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                </tr>  
                <tr>
                  <td>07/09/2017</td>
                  <td>902111</td>
                  <td>Cheques - Parcela 2/4 - DELL Computadores</td>
                  <td>2.024,66</td>
                  <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                </tr>  
                <tr>
                  <td>07/09/2017</td>
                  <td>902112</td>
                  <td>Cheques - Parcela 3/4 - DELL Computadores</td>
                  <td>2.024,66</td>
                  <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                </tr>  
                <tr>
                  <td>07/09/2017</td>
                  <td>902113</td>
                  <td>Cheques - Parcela 4/4 - DELL Computadores</td>
                  <td>2.024,66</td>
                  <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                </tr>                                                                                                 
                <tr>
                  <td></td>
                  <td></td>
                  <td style="font-weight: bold;">TOTAL</td>                  
                  <td style="font-weight: bold; color: red">R$ 9.562,51</td>                  
                  <td></td>
                </tr>                
              </table>                                                                              
            </section>
          </div>                    
          <!-- Fim Despesas a Compensar-->

          <!-- Inicio Carteira de Conbrança-->
          <div class="tab-pane" id="carteira">
          <section id="new">              
              <table class="table table-striped">
                <tr>
                  <th>Data</th>
                  <th>Num. Doc.</th>
                  <th>Descrição</th>
                  <th>Valor</th>
                  <th style="width: 10px"></th>
                </tr>
                <tr>
                  <td>07/09/2017</td>
                  <td>1014B072018</td>
                  <td>Recebimento de Acordo</td>
                  <td>1.463,87</td>
                  <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                </tr>          
                <tr>
                  <td>10/09/2017</td>
                  <td>1044B072018</td>
                  <td>Recebimento de Acordo</td>
                  <td>2.365,23</td>
                  <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                </tr>  
                <tr>
                  <td>01/09/2017</td>
                  <td>3062EB062018</td>
                  <td>Taxa de Condominio</td>
                  <td>266,74</td>
                  <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                </tr>                                        
                <tr>
                  <td></td>
                  <td></td>
                  <td style="font-weight: bold;">TOTAL</td>                  
                  <td style="font-weight: bold; color: green">R$ 4.095,84</td>                  
                  <td></td>
                </tr>                
              </table>                                                                              
            </section>
          </div>              
          <!-- Fim Carteira de Conbrança-->

        </div>
        <!-- Fim conteúdo-->          
    </div>
   <!-- Fim Prestação/Extrato-->       
  </div>
</section>

