<!--?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();       
?-->
<section class="content-header">
  <h1>
    Prestação de Contas
  </h1>
</section>

<section class="content">    
  <div class="row">

    <!-- Início Período-->
    <div class="col-xs-4" style="min-width: 400px;">
      <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="box-title">Período</h3>                      
        </div>

        <div class="box-body">
          <div class="col-md-16">

          <!-- Início Ano-->
            <div class="form-group" style="width: 100px; float:left; margin-right:10px;">
              <label>Ano</label>
              <select class="form-control select2">
                <option selected="selected">2018</option>
                <option>2017</option>
                <option>2016</option>
                <option>2015</option>
              </select>
            </div>
           <!-- Fim Ano--> 
           <!-- Início Mês-->
            <div class="form-group" style="width: 100px; float:left;">
              <label>Mês</label>
              <select class="form-control select2">
                <option selected="selected">12</option>
                <option>11</option>
                <option>10</option>
                <option>09</option>
                <option>08</option>
                <option>07</option>
                <option>06</option>
                <option>05</option>
                <option>04</option>
                <option>03</option>
                <option>02</option>
                <option>01</option>
              </select>
            </div>
            <!-- Fim Mês-->
            <!-- Início Botões-->
            <div class="row" style="width: 40px; float:left; margin-left:10px;">
              <button type="button" title="Iniciar Nova Prestação" class="btn btn-block btn-success"><i class="fa fa-plus"></i></button>
              <button type="button" title="Buscar Taxa de Condomínio" class="btn btn-block btn-info"><i class="fa fa-search"></i></button>
            </div>
            <div class="row" style="width: 40px; float:left; margin-left:25px;">
              <button type="button" title="Fechar Prestação" class="btn btn-block btn-primary"><i class="fa fa-lock"></i></button>              
              <button type="button" title="Imprimir Prestação" class="btn btn-block btn-info"><i class="fa fa-print"></i></button>              
            </div>            
            <!-- Fim Botões-->

          </div>
        </div>
      </div>
    </div>
    <!-- Fim Período-->

   <!-- Início Prestação/Extrato-->
   <div class="col-xs-12">
      <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
          <li class=""><a href="#resumo"     onClick='Envio_Ajax("POST", "tabelaPC", "load_div", "Home", "exibir","opc=prestacaoContas&act=listarOPC&tela=pc&desc=Prestacao de Contas");   return false;' data-toggle="tab">Prestação de Contas</a></li>
          <li class=""><a href="#documentos" onClick='Envio_Ajax("POST", "tabelaPC", "load_div", "Home", "exibir","opc=prestacaoContas&act=listarOPC&tela=doc&desc=Prestacao de Contas");  return false;' data-toggle="tab">Documentos</a></li>
          <li class=""><a href="#extrato"    onClick='Envio_Ajax("POST", "tabelaPC", "load_div", "Home", "exibir","opc=prestacaoContas&act=listarOPC&tela=ext&desc=Prestacao de Contas");  return false;' data-toggle="tab">Extrato</a></li>
          <li class=""><a href="#despesas"   onClick='Envio_Ajax("POST", "tabelaPC", "load_div", "Home", "exibir","opc=prestacaoContas&act=listarOPC&tela=rdef&desc=Prestacao de Contas"); return false;' data-toggle="tab">Reconhecimento das Despesas de Exercícios Futuros</a></li>
          <li class=""><a href="#carteira"   onClick='Envio_Ajax("POST", "tabelaPC", "load_div", "Home", "exibir","opc=prestacaoContas&act=listarOPC&tela=rref&desc=Prestacao de Contas"); return false;' data-toggle="tab">Reconhecimento das Receitas de Exercícios Futuros</a></li>
        </ul>
      
        <!-- Início conteúdo-->
        <div class="tab-content" id="tabelaPC"></div>
        <!-- Fim conteúdo-->          

    </div>
   <!-- Fim Prestação/Extrato-->       
  </div>
</section>

