<!--?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();       
?-->
<!-- Inicio Documentos-->
<div class="tab-pane active" id="documentos">
  <section id="new">
    <button type="button" title="Iniciar Nova Prestação" data-toggle="modal" data-target="#myAddDoc" class="btn btn-block btn-success"><i
        class="fa fa-plus"></i></button>
    <!-- Modal -->
    <div class="modal fade" id="myAddDoc" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <!--Botão para fechar tela Modal-->
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Adicionar Documento</h4>
          </div>
          <!--/.modal-header-->
          <div class="modal-body" style="background-color: #ecf0f5; padding: 10px">
            <form>
              <!-- Inicio Form Documento-->
              <div class="box box-default">
                <div class="box-header with-border">
                  <h3 class="box-title">Documento Fiscal</h3>
                </div>

                <div class="box-body">
                  <div class="col-md-16">

                    <!-- Início Tipo-->
                    <div class="form-group" style="width: 110px; float:left; margin-right:10px;">
                      <label>Grupo</label>
                      <select class="form-control select2">
                        <option>Receitas</option>
                        <option selected="selected">Despesas</option>
                      </select>
                    </div>
                    <!-- Fim Tipo-->

                    <!-- Início Conta-->
                    <div class="form-group" style="width: 280px; float:left; margin-right:10px;">
                      <label>Conta</label>
                      <select class="form-control select2">
                        <option>Honorário Contábeis</option>
                        <option>Pro-Lábore Síndico</option>
                        <option>Energia</option>
                        <option>Materiais de Limpeza</option>
                        <option selected="selected">Equipamentos de Informática</option>
                      </select>
                    </div>
                    <!-- Fim Conta-->

                    <!-- Início Tipo-->
                    <div class="form-group" style="width: 150px; float:left;">
                      <label>Tipo</label>
                      <select class="form-control select2">
                        <option selected="selected">Nota Fiscal</option>
                        <option>Cupom Fiscal</option>
                        <option>Contra-Cheque</option>
                        <option>Imposto</option>
                      </select>
                    </div>
                    <!-- Fim Tipo-->

                    <!-- Início Descrição-->
                    <div class="form-group" style="width: 100%; float:left;">
                      <div>
                        <div class="form-group" style="width: 170px; float:left; margin-right:20px;">
                          <label for="example-input-1">Data Emissão</label>
                          <input type="date" class="form-control" id="example-input-1">
                        </div>
                        <div class="form-group" style="width: 150px; float:left; margin-right:20px;">
                          <label for="example-input-1">Identificação</label>
                          <input type="text" class="form-control" id="example-input-1">
                        </div>
                        <div class="form-group" style="width: 150px; float:left;">
                          <label for="example-input-1">Valor Total Documento</label>
                          <input type="number" class="form-control" id="example-input-1">
                        </div>
                        <div style="clear: both;"></div>
                      </div>
                      <div>
                        <label for="example-input-1">Descrição</label>
                        <input type="text" class="form-control" id="example-input-1">
                      </div>
                    </div>
                    <!-- Fim Descrição-->
                  </div>
                </div>
              </div>
              <!-- Fim Form Documento-->

              <!-- Inicio Form Reconhecimento Futuro-->
              <div class="box box-default">
                <div class="box-header with-border">
                  <h3 class="box-title">Reconhecer para Exercícios Futuros</h3>
                </div>

                <table class="table table-striped">
                  <tr>
                    <th>Identificação</th>
                    <th>Descrição</th>
                    <th>Valor</th>
                    <th style="width: 10px"></th>
                  </tr>
                  <tr>
                    <td style="width: 10px"><input type="text" class="form-control" id="example-input-1" value="902110" /></td>
                    <td style="width: 250px"><input type="text" class="form-control" id="example-input-1" value="Parcela 2/5 - DELL Computadores" /></td>
                    <td style="width: 100px"><input type="text" class="form-control" id="example-input-1" value="2.092,77" /></td>
                    <td><i class="fa fa-trash"></i> </td>
                  </tr>
                  <tr>
                    <td style="width: 10px"><input type="text" class="form-control" id="example-input-1" value="902111" /></td>
                    <td style="width: 250px"><input type="text" class="form-control" id="example-input-1" value="Parcela 3/5 - DELL Computadores" /></td>
                    <td style="width: 100px"><input type="text" class="form-control" id="example-input-1" value="2.092,77" /></td>
                    <td><i class="fa fa-trash"></i> </td>
                  </tr>
                </table>
                <div class="modal-footer">
                  <button type="button" class="btn btn-success"><i class="fa fa-plus"></i></button>
                </div>
                <!--/.modal-footer-->
              </div>

              <!-- Fim Form Reconhecimento Futuro-->

              <!-- Inicio Form Extrato-->
              <div class="box box-default">
                <div class="box-header with-border">
                  <h3 class="box-title">Identificar no Extrato Bancário</h3>
                </div>

                <div class="box-body">
                  <div class="col-md-16">
                    <input style="width: 150px; float:left; margin-right:20px;" type="number" class="form-control" id="example-input-1"
                      disabled>
                    <button style="width: 150px; float:left; margin-right:20px;" type="button" title="Localizar lançamento no Extrato"
                      class="btn btn-block btn-info"><i class="fa fa-sync"></i>Buscar</button>
                    <p> Identificação no Extrato: <b>902114</b></p>
                  </div>
                </div>
              </div>
              <!-- Fim Form Extrato-->

              <div style="clear: both;"></div>
            </form>
          </div>
          <!--/.modal-body-->
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            <button type="button" class="btn btn-success">Adicionar</button>
          </div>
          <!--/.modal-footer-->
        </div>
        <!--/.modal-content-->
      </div>
      <!--/modal-dialog-->
    </div>
    <table class="table table-striped">
      <tr>
        <th>Data Emissão</th>
        <th>Num. Doc.</th>
        <th>Descrição</th>
        <th>Valor</th>
        <th style="width: 10px"></th>
      </tr>
      <tr>
        <td>07/09/2017</td>
        <td>12345-2</td>
        <td>DELL Computadores</td>
        <td>10.463,87</td>
        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
      </tr>
      <tr>
        <td>10/09/2017</td>
        <td>1234-56</td>
        <td>Supermercado ABC</td>
        <td>2.365,23</td>
        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
      </tr>
      <tr>
        <td>01/09/2017</td>
        <td>08/2017</td>
        <td>Pro-lábore - Síndico</td>
        <td>2.500,00</td>
        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td style="font-weight: bold;">TOTAL</td>
        <td style="font-weight: bold;">R$ 15.329,10</td>
        <td></td>
      </tr>
    </table>
  </section>
</div>
<!-- Fim Documentos-->