<?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();  
    $header  = $valores['header'];     
    $extrato = $valores['extrato'];  
    $saldo   = $valores['saldo'];  
?>

<section id="new">
  <div>
    <h5>Banco: <img style="width: 20px;" src="Views/Sistema/Admin/images/<?= $header['Banco-img']?>.png" alt="img-Banco"> 
      <b><?= $header['Banco']?></b></h5>
      <h5>Cliente: <b><?= $header['Cliente']?></b></h5>
      <h5>Conta:   <b><?= $header['Conta']?></b></h5>
      <h5>Data:    <b><?= $header['Data']?></b></h5>
      <h5>Período: <b><?= $header['Periodo']?></b></h5>
  </div>

  <!-- Inicio Importar arquivo Extrato -->
  <form id="salvarDoc" enctype="multipart/form-data">
    <input type="hidden" name="rota" value="PrestacaoContas" />
    <input type="hidden" name="acao" value="listarEXT" />
    <input type="hidden" name="titulo" value="Prestacao de Contas" />
    <input type="hidden" name="banco" value="bb" />
    <input type="hidden" name="ag" value="1234" />
    <input type="hidden" name="op" value="003" />
    <input type="hidden" name="conta" value="12345678-9" />

    <div class="form-group">
      <div class="input-group input-file" name="Fichier1">
        <span class="input-group-btn">
              <button class="btn btn-info btn-choose" type="button"><i class="fa fa-fw fa-cloud-upload"></i> Selecionar
      Arquivo</button>
        </span>
        <input type="text" class="form-control" id="inputArq" placeholder='Selecionar arquivo...' />
        <span class="input-group-btn">
          <button class="btn btn-success" disabled id="enviaArq" type="button"><i class="fa fa-fw fa-flash "></i></button>              
        </span>  
      </div>      
    </div>
  </form>
</div>  
<div style="clear: both;"></div>

  <table class="table table-striped">
    <tr>
      <th>Data</th>
      <th>Num. Doc.</th>
      <th>Descrição</th>
      <th>Valor</th>
      <th>Saldo</th>
      <th style="width: 10px"></th>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td style="font-weight: bold;">SALDO ANTERIOR</td>
      <td>=====</td>
      <td style="font-weight: bold;">R$ <?= $saldo['Inicial'];?></td>
      <td></td>
    </tr>
    
    <?php foreach ($extrato as $key => $lancamento) { ?>    
      <tr>
        <td><?= $lancamento['Data']?></td>
        <td><?= $lancamento['NumDoc']?></td>
        <td><?= $lancamento['Desc']?></td>
        <td style="color: <?= $lancamento['ValorCor']?>"><?= $lancamento['Valor']?></td>
        <td><?= $lancamento['Saldo']?></td>
        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
      </tr>
    <?php }?>

    <tr>      
      <td></td>
      <td></td>
      <td style="font-weight: bold;">SALDO FINAL</td>
      <td>=====</td>
      <td style="font-weight: bold;">R$ <?= $saldo['Final']; ?></td>
      <td></td>
    </tr>
  </table>

</section>

<script>
bs_input_file();

$(document).on('click', '#enviaArq', function(e){
  var form = new FormData(salvarDoc);
  form.append('ext', $('#inp_extrato').get(0).files[0]); // para apenas 1 arquivo
  requisitarServidor("index.php", "", form, "banco");
});
</script>