<!--?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();       
?-->
<!-- Início conteúdo Prestação-->
<div class="tab-pane active" id="resumo">
  <section id="new">

    <!-- Início Tabela Receita-->
    <div style="width:100%;">
      <div class="div_table_receita div_table">
        <div class="box-header">
          <h3 class="box-title"><b>Receitas</b></h3>
        </div>
        <div class="box-body no-padding">
          <table class="table table-striped">
            <tr>
              <td>Saldo Transportado</td>
              <td>10.000,00</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Taxas de Condominio</td>
              <td>33.754,16</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Juros sobre Taxas de Condominio</td>
              <td>320,84</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Reconhecimento das Receitas de Exercícios Futuros</td>
              <td>4.095,84</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Juros Bancários</td>
              <td>55,25</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Recebimento de Acordos</td>
              <td>38.873,17</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>TOTAL</td>
              <td>R$ <b>87.099,26</b></td>
              <td></td>
            </tr>
          </table>
        </div>
      </div>
      <div style="clear: both;"></div>
    </div>
    <!-- Fim Tabela Receita-->

    <!-- Início Tabela Administrativas/Diversos-->
    <div style="width:100%;">
      <!-- Início Tabela Despesas Administrativas-->
      <div class="div_table_despesas div_table">
        <div class="box-header">
          <h3 class="box-title"><b>Despesas - Administrativas</b></h3>
        </div>
        <div class="box-body no-padding">
          <table class="table table-striped">
            <tr>
              <td>Honorário Contábeis</td>
              <td>1.836,52</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Pro-Lábore Síndico</td>
              <td>2.500,00</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Celg</td>
              <td>1.211,34</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>TOTAL</td>
              <td>R$ <b>5.547,86</b></td>
              <td></td>
            </tr>
          </table>
        </div>
      </div>
      <!-- Fim Tabela Despesas Administrativas-->

      <!-- Início Tabela Despesas Diversas-->
      <div class="div_table_despesas div_table">
        <div class="box-header">
          <h3 class="box-title"><b>Despesas - Diversas</b></h3>
        </div>
        <div class="box-body no-padding">
          <table class="table table-striped">
            <tr>
              <td>Descontos sobre Taxas de Condominio</td>
              <td>20,84</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Reconhecimento das Despesas de Exercicios Futuros</td>
              <td>9.562,51</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Materiais de Limpeza</td>
              <td>2.365,23</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Equipamentos de Informática</td>
              <td>2.092,78</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>TOTAL</td>
              <td>R$ <b>14.041,36</b></td>
              <td></td>
            </tr>
          </table>
        </div>
      </div>
      <!-- Fim Tabela Despesas Diversas-->

      <div style="clear: both;"></div>
    </div>
    <!-- Fim Despesas Administrativas/Diversos-->

    <!-- Início Tabela Despesas EncargosSociais/Bancarios-->
    <div style="width:100%;">
      <!-- Início Tabela Despesas - Encargos Sociais-->
      <div class="div_table_despesas div_table">
        <div class="box-header">
          <h3 class="box-title"><b>Despesas - Encargos Sociais</b></h3>
        </div>
        <div class="box-body no-padding">
          <table class="table table-striped">
            <tr>
              <td>FGTS</td>
              <td>1.134,92</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>TOTAL</td>
              <td>R$ <b>1.134,92</b></td>
              <td></td>
            </tr>
          </table>
        </div>
      </div>
      <!-- Fim Tabela Despesas - Encargos Sociais-->

      <!-- Início Tabela Despesas Bancáriais-->
      <div class="div_table_despesas div_table">
        <div class="box-header">
          <h3 class="box-title"><b>Despesas - Bancárias</b></h3>
        </div>
        <div class="box-body no-padding">
          <table class="table table-striped">
            <tr>
              <td>Tarifa Bancária</td>
              <td>1.416,80</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>TOTAL</td>
              <td>R$ <b>1.416,80</b></td>
              <td></td>
            </tr>
          </table>
        </div>
      </div>
      <!-- Fim Tabela Despesas Bancárias-->

      <div style="clear: both;"></div>
    </div>
    <!-- Fim Despesas EncargosSociais/Bancarios-->

    <!-- Inicio Saldo a Transportar-->
    <div style="width:100%">
      <div class="div_table_result">
        <div class="box-body no-padding">
          <table class="table table-striped">
            <tr>
              <td>Receitas</td>
              <td style="color: green;"><b>+ 87.099,26</b></td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Despesas</td>
              <td style="color: red;"><b>- 22.140,94</b></td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Saldo a Transportar</td>
              <td style="color: green;">R$ <b>64.958,32</b></td>
              <td></td>
            </tr>
          </table>
        </div>
      </div>
      <div style="clear: both;"></div>
    </div>
    <!-- Fim Saldo a Transportar-->

    <hr>

    <div style="width:100%;">
      <!-- Início Tabela Informe Adminsitrativo-->
      <div class="div_table_result div_table_bancario div_table">
        <div class="box-header">
          <h3 class="box-title"><b>Saldo Bancário - 30/09/2017</b></h3>
        </div>
        <div class="box-body no-padding">
          <table class="table table-striped">
            <tr>
              <td>Saldo Conta Corrente | 1234 / 003 / 12345678-9</td>
              <td>3.696,26</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Saldo Conta Poupança | 1234 / 013 / 12345678-9</td>
              <td>39.717,38</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>TOTAL</td>
              <td>R$ <b>43.413,64</b></td>
              <td></td>
            </tr>
          </table>
        </div>
      </div>
      <!-- Fim Tabela Informe Administrativo-->
      <div style="clear: both;"></div>
    </div>

    <!-- Início Tabela Demostrativos a Receber/Pagar-->
    <div style="width:100%;">
      <!-- Início Tabela Receitas de Exercícios Futuros-->
      <div class="div_table_receita div_table">
        <div class="box-header">
          <h3 class="box-title"><b>Reconhecimento das Receitas de Exercícios Futuros</b></h3>
        </div>
        <div class="box-body no-padding">
          <table class="table table-striped">
            <tr>
              <td>Recebimento de Acordo (1014B072018)</td>
              <td>1.463,87</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Recebimento de Acordo (1044B072018)</td>
              <td>2.365,23</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Taxa de Condominio (3062EB062018)</td>
              <td>266,74</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>TOTAL</td>
              <td>R$ <b>4.095,84</b></td>
              <td></td>
            </tr>
          </table>
        </div>
      </div>
      <!-- Fim Tabela Receitas de Exercícios Futuros-->

      <!-- Início Tabela Despesas de Exercicios Futuros-->
      <div class="div_table_despesas div_table">
        <div class="box-header">
          <h3 class="box-title"><b>Reconhecimento das Despesas de Exercicios Futuros</b></h3>
        </div>
        <div class="box-body no-padding">
          <table class="table table-striped">
            <tr>
              <td>Cheque (902109) - MB Vidros</td>
              <td>1.463,87</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Cheques (902110) - Parcela 1/4 - NF:12345-2 - DELL Computadores</td>
              <td>2.024,66</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Cheques (902111) - Parcela 2/4 - NF:12345-2 - DELL Computadores</td>
              <td>2.024,66</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Cheques (902112) - Parcela 3/4 - NF:12345-2 - DELL Computadores</td>
              <td>2.024,66</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Cheques (902113) - Parcela 4/4 - NF:12345-2 - DELL Computadores</td>
              <td>2.024,66</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>TOTAL</td>
              <td>R$ <b>9.562,51</b></td>
              <td></td>
            </tr>
          </table>
        </div>
      </div>
      <!-- Fim Tabela Despesas a Pagar-->
      <div style="clear: both;"></div>
    </div>
    <!-- Fim Tabela Demostrativos a Receber/Pagar-->

    <!-- Início Tabela Demostrativos a Receber/Pagar Realizados-->
    <div style="width:100%;">
      <!-- Início Tabela Informe Adminsitrativo-->
      <div class="div_table_receita div_table">
        <div class="box-header">
          <h3 class="box-title"><b>Compensação das Receitas de Exercicios Passados</b></h3>
        </div>
        <div class="box-body no-padding">
          <table class="table table-striped">
            <tr>
              <td>Taxa de Condominio (3062EB092018)</td>
              <td>372,74</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>TOTAL</td>
              <td>R$ <b>372,74</b></td>
              <td></td>
            </tr>
          </table>
        </div>
      </div>
      <!-- Fim Tabela Informe Administrativo-->

      <!-- Início Tabela Despesas a Compensar-->
      <div class="div_table_despesas div_table">
        <div class="box-header">
          <h3 class="box-title"><b>Compensação das Despesas de Exercicios Passados</b></h3>
        </div>
        <div class="box-body no-padding">
          <table class="table table-striped">
            <tr>
              <td>Cheque (902234) - Jardinagem</td>
              <td>463,87</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Cheques (902108) - NF:1235645-2 - Gás</td>
              <td>2.371,09</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>TOTAL</td>
              <td>R$ <b>2.834,96</b></td>
              <td></td>
            </tr>
          </table>
        </div>
      </div>
      <!-- Fim Tabela Despesas a Compensar-->
      <div style="clear: both;"></div>
    </div>
    <!-- Fim Demostrativos a Receber/Pagar Realizados-->

    <!-- Início Tabela Demonstrativo Saldo-->
    <div style="width:100%">
      <div class="div_table_result">
        <div class="box-body no-padding">
          <table class="table table-striped">
            <tr>
              <td>Saldo Bancário</td>
              <td style="color: green;">+ 43.413,64</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Reconhecimento das Receitas de Exercicios Futuros</td>
              <td style="color: green;">+ 4.095,84</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Compensação das Receitas de Exercicios Passados</td>
              <td style="color: red;">- 372,74</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Reconhecimento das Despesas de Exercicios Futuros</td>
              <td style="color: red;">- 9.562,51</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Compensação das Despesas de Exercicios Passados</td>
              <td style="color: green;">+2.834,96</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Caixa</td>
              <td style="color: green;">+ 24.549,13</td>
              <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i
                    class="fa fa-fw fa-info"></i></button></td>
            </tr>
            <tr>
              <td>Saldo a Transportar em <b>30/09/2017</b></td>
              <td style="color: green;">R$ <b>64.958,32</b></td>
              <td></td>
            </tr>
          </table>
        </div>
      </div>
      <div style="clear: both;"></div>
    </div>
    <!-- Fim Tabela Demonstrativo Saldo-->

  </section>
</div>
<!-- Fim conteúdo Prestação-->