<!--?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();       
?-->
<!-- Inicio Carteira de Conbrança-->
<div class="tab-pane active" id="carteira">
  <section id="new">
    <table class="table table-striped">
      <tr>
        <th>Data</th>
        <th>Num. Doc.</th>
        <th>Descrição</th>
        <th>Valor</th>
        <th style="width: 10px"></th>
      </tr>
      <tr>
        <td>07/09/2017</td>
        <td>1014B072018</td>
        <td>Recebimento de Acordo</td>
        <td>1.463,87</td>
        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
      </tr>
      <tr>
        <td>10/09/2017</td>
        <td>1044B072018</td>
        <td>Recebimento de Acordo</td>
        <td>2.365,23</td>
        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
      </tr>
      <tr>
        <td>01/09/2017</td>
        <td>3062EB062018</td>
        <td>Taxa de Condominio</td>
        <td>266,74</td>
        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td style="font-weight: bold;">TOTAL</td>
        <td style="font-weight: bold; color: green">R$ 4.095,84</td>
        <td></td>
      </tr>
    </table>
  </section>
</div>
<!-- Fim Carteira de Conbrança-->