<?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();       
?>
<section class="content-header">
  <h1>
    Prestação de Contas
  </h1>
</section>

<section class="content">    
  <div class="row">

    <!-- Início Período-->
    <div class="col-xs-4" style="min-width: 400px;">
      <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="box-title">Período</h3>                      
        </div>

        <div class="box-body">
          <div class="col-md-16">

          <!-- Início Ano-->
            <div class="form-group" style="width: 100px; float:left; margin-right:10px;">
              <label>Ano</label>
              <select class="form-control select2">
                <option selected="selected">2018</option>
                <option>2017</option>
                <option>2016</option>
                <option>2015</option>
              </select>
            </div>
           <!-- Fim Ano--> 
           <!-- Início Mês-->
            <div class="form-group" style="width: 100px; float:left;">
              <label>Mês</label>
              <select class="form-control select2">
                <option selected="selected">12</option>
                <option>11</option>
                <option>10</option>
                <option>09</option>
                <option>08</option>
                <option>07</option>
                <option>06</option>
                <option>05</option>
                <option>04</option>
                <option>03</option>
                <option>02</option>
                <option>01</option>
              </select>
            </div>
            <!-- Fim Mês-->
            <!-- Início Botões-->
            <div class="row" style="width: 40px; float:left; margin-left:10px;">
              <button type="button" title="Iniciar Nova Prestação" class="btn btn-block btn-success"><i class="fa fa-plus"></i></button>
              <button type="button" title="Editar Prestação" class="btn btn-block btn-warning"><i class="fa fa-edit"></i></button>
            </div>
            <div class="row" style="width: 40px; float:left; margin-left:25px;">
              <button type="button" title="Fechar Prestação" class="btn btn-block btn-primary"><i class="fa fa-lock"></i></button>              
              <button type="button" title="Imprimir Prestação" class="btn btn-block btn-primary"><i class="fa fa-print"></i></button>              
            </div>            
            <!-- Fim Botões-->

          </div>
        </div>
      </div>
    </div>
    <!-- Fim Período-->

   <!-- Início Prestação/Extrato-->
   <div class="col-xs-12">
      <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#resumo"   data-toggle="tab">Prestação de Contas</a></li>
          <li class="">      <a href="#extrato"  data-toggle="tab">Extrato</a></li>
          <li class="">      <a href="#despesas"   data-toggle="tab">Despesas a Compensar</a></li>
          <li class="">      <a href="#carteira" data-toggle="tab">Carteira de Cobrança</a></li>
        </ul>
      
        <!-- Início conteúdo-->
        <div class="tab-content">

          <!-- Início conteúdo Prestação-->
          <div class="tab-pane active" id="resumo">
            <section id="new">
                          
              <!-- Início Tabela Receita-->
              <div style="width:100%;">
                <div class="div_table_receita div_table">
                  <div class="box-header"><h3 class="box-title"><b>Receitas</b></h3></div>            
                  <div class="box-body no-padding">
                    <table class="table table-striped">
                      <tr>
                        <td>Taxas de Condominio</td>
                        <td>34.095,84</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>  
                      <tr>
                        <td>Carteira de Cobrança</td>
                        <td>4.095,84</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                                      
                      <tr>
                        <td>Juros Bancários</td>
                        <td>55,25</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>               
                      <tr>
                        <td>Recebimento de Acordos</td>
                        <td>38.873,17</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>             
                      <tr>
                        <td>TOTAL</td>
                        <td>R$ <b>77.120,10</b></td>                        
                        <td></td>
                      </tr>                  
                    </table>                                        
                  </div>                
                </div>                                      
                <div style="clear: both;"></div>
              </div> 
              <!-- Fim Tabela Receita-->

              <!-- Início Tabela Administrativas/Diversos-->
              <div style="width:100%;">
                <!-- Início Tabela Despesas Administrativas-->
                <div class="div_table_despesas div_table">
                  <div class="box-header"><h3 class="box-title"><b>Despesas Administrativas</b></h3></div>            
                  <div class="box-body no-padding">
                    <table class="table table-striped">
                      <tr>
                        <td>Honorário Contábeis</td>
                        <td>1.836,52</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>               
                      <tr>
                        <td>Celg</td>
                        <td>1.211,34</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>               
                      <tr>
                        <td>TOTAL</td>
                        <td>R$ <b>3.047,86</b></td>                       
                        <td></td>
                      </tr>                                                    
                    </table>                                        
                  </div>
                </div>
                <!-- Fim Tabela Despesas Administrativas-->

                <!-- Início Tabela Despesas Diversas-->
                <div class="div_table_despesas div_table">
                  <div class="box-header"><h3 class="box-title"><b>Despesas Diversas</b></h3></div>            
                  <div class="box-body no-padding">
                    <table class="table table-striped">
                      <tr>
                        <td>Materiais de Limpeza</td>
                        <td>739,30</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>      
                      <tr>
                        <td>Cheque (902109) - MB Vidros</td>
                        <td>1.463,87</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                                            
                      <tr>
                        <td>TOTAL</td>
                        <td>R$ <b>2.203,17</b></td>
                        <td></td>
                      </tr>                                                    
                    </table>                                        
                  </div>
                </div>
                <!-- Fim Tabela Despesas Diversas-->
                
                <div style="clear: both;"></div>
              </div> 
              <!-- Fim Despesas Administrativas/Diversos-->

              <!-- Início Tabela Despesas EncargosSociais/Bancarios-->
              <div style="width:100%;">
                <!-- Início Tabela Despesas - Encargos Sociais-->
                <div class="div_table_despesas div_table">
                  <div class="box-header"><h3 class="box-title"><b>Despesas - Encargos Sociais</b></h3></div>            
                  <div class="box-body no-padding">
                    <table class="table table-striped">
                      <tr>
                        <td>FGTS</td>
                        <td>1.134,92</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                         
                      <tr>
                        <td>TOTAL</td>
                        <td>R$ <b>1.134,92</b></td>
                        <td></td>
                      </tr>                                                    
                    </table>                                        
                  </div>
                </div>
                <!-- Fim Tabela Despesas - Encargos Sociais-->

                <!-- Início Tabela Despesas Bancáriais-->
                <div class="div_table_despesas div_table">
                  <div class="box-header"><h3 class="box-title"><b>Despesas - Bancárias</b></h3></div>            
                  <div class="box-body no-padding">
                    <table class="table table-striped">
                      <tr>
                        <td>Tarifa Bancária</td>
                        <td>1.416,80</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                         
                      <tr>
                        <td>TOTAL</td>
                        <td>R$ <b>1.416,80</b></td>
                        <td></td>
                      </tr>                                                    
                    </table>                                                      
                  </div>
                </div>
                <!-- Fim Tabela Despesas Bancárias-->
                
                <div style="clear: both;"></div>
              </div> 
              <!-- Fim Despesas EncargosSociais/Bancarios-->

              <!-- Inicio Saldo a Transportar-->
              <div style="width:100%">
                <div class="div_table_result">
                  <div class="box-body no-padding">
                  <table class="table table-striped">
                    <tr>
                      <td>Receitas</td>
                      <td style="color: green;"><b>+ 77.120,10</b></td>
                      <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                    </tr>               
                    <tr>
                      <td>Despesas</td>
                      <td style="color: red;"><b>- 7.802,75</b></td>
                      <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                    </tr>               
                    <tr>
                      <td>Saldo a Transportar</td>
                      <td style="color: green;">R$ <b>69.317,35</b></td>
                      <td></td>
                    </tr>                                                    
                  </table>                                        
                  </div>                
                </div>                                      
                <div style="clear: both;"></div>
              </div>                                                   
              <!-- Fim Saldo a Transportar-->              

              <!-- Início Tabela Despesas Demostrativos-->
              <div style="width:100%;">
                <!-- Início Tabela Informe Adminsitrativo-->
                <div class="div_table_bancario div_table">
                  <div class="box-header"><h3 class="box-title"><b>Saldo Bancário - 30/09/2017</b></h3></div>            
                  <div class="box-body no-padding">
                    <table class="table table-striped">
                      <tr>
                        <td>Saldo Conta Corrente | 1234 / 003 / 12345678-9</td>
                        <td>9.466,90</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>         
                      <tr>
                        <td>Saldo Conta Poupança | 1234 / 013 / 12345678-9</td>
                        <td>36.341,97</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                                               
                      <tr>
                        <td>TOTAL</td>
                        <td>R$ <b>45.808,87</b></td>
                        <td></td>
                      </tr>                                                    
                    </table>                                        
                  </div>
                </div>
                <!-- Fim Tabela Informe Administrativo-->

                <!-- Início Tabela Despesas a Compensar-->
                <div class="div_table_despesas div_table">
                  <div class="box-header"><h3 class="box-title"><b>Despesas a Compensar</b></h3></div>            
                  <div class="box-body no-padding">
                    <table class="table table-striped">
                      <tr>
                        <td>Cheque (902109) - MB Vidros</td>
                        <td>1.463,87</td>
                        <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                                             
                      <tr>
                        <td>TOTAL</td>
                        <td>R$ <b>1.463,87</b></td>
                        <td></td>
                      </tr>                                                    
                    </table>                                        
                  </div>
                </div>                
                <!-- Fim Tabela Despesas a Compensar-->              
                <div style="clear: both;"></div>
              </div> 
              <!-- Fim Demonstrativos-->

              <!-- Início Tabela Demonstrativo Saldo-->
              <div style="width:100%">
                <div class="div_table_result">
                  <div class="box-body no-padding">
                  <table class="table table-striped">
                    <tr>
                      <td>Saldo Bancário</td>
                      <td style="color: green;">+ 45.808,87</td>
                      <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                    </tr>  
                    <tr>
                      <td>Carteira de Cobrança</td>
                      <td style="color: green;">+ 4.095,84</td>
                      <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                    </tr>                                  
                    <tr>
                      <td>Despesas a Compensar</td>
                      <td style="color: red;">- 1.463,87</td>
                      <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                    </tr>               
                    <tr>
                      <td>Caixa</td>
                      <td style="color: green;">+ 20.876,41</td>
                      <td><button type="button" title="Detalhar" style="padding:1px; width:auto;" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                    </tr>                                   
                    <tr>
                      <td>Saldo a Transportar em <b>30/09/2017</b></td>
                      <td style="color: green;">R$ <b>69.317,35</b></td>
                      <td></td>
                    </tr>                                                    
                  </table>                                        
                  </div>                
                </div>                                      
                <div style="clear: both;"></div>
              </div>                                                                 
              <!-- Fim Tabela Demonstrativo Saldo-->
                
            </section>
          </div>
          <!-- Fim conteúdo Prestação-->

          <!-- Início conteúdo Extrato-->
          <div class="tab-pane" id="extrato">
            <section id="new">
            <!-- Início Contas-->  
            <div class="nav-tabs-custom">
              <ul class="nav nav-tabs">
                <li class="active"><a href="#ccCaixa" data-toggle="tab"><img style="width: 20px;" src="Views/Sistema/admin/images/caixa.png" alt="caixa"></span> Conta Corrente<span class="logo-lg"></a></li>
                <li class="">      <a href="#cpBB" data-toggle="tab"><img style="width: 20px;" src="Views/Sistema/admin/images/bb.png" alt="bb"></span> Conta Poupança<span class="logo-lg"></a></li>
              </ul>

              <!-- Início conteúdo Contas-->
              <div class="tab-content">

                <!-- Início conteúdo ContaCorrente-->
                <div class="tab-pane active" id="ccCaixa">
                  <section id="new">
                    <div>
                      <h5>Banco: <img style="width: 20px;" src="Views/Sistema/admin/images/caixa.png" alt="caixa"> <b>Caixa Econômica Federal</b></h6>
                      <h5>Cliente: <b>Condomínio Residencial AAAAAA</b></h5>
                      <h5>Conta: <b>1234 / 003 / 12345678-9</b></h5>
                      <h5>Data: <b>01/10/2017 - 12:03</b></h5>          
                      <h5>Mês: <b>Setembro/2017</b></h5>
                    </div>
                    <button type="button" class="btn btn-block btn-info"><i class="fa fa-fw fa-cloud-upload"></i> Importar Extrato</button>
                    <table class="table table-striped">
                      <tr>
                        <th>Data</th>
                        <th>Num. Doc.</th>
                        <th>Descrição</th>
                        <th>Valor</th>
                        <th>Saldo</th>
                        <th style="width: 10px"></th>
                      </tr>
                      <tr>
                        <td style="font-weight: bold;">01/09/2017</td>
                        <td></td>
                        <td style="font-weight: bold;">SALDO ANTERIOR</td>
                        <td>=====</td>
                        <td style="font-weight: bold;">R$ 15.151,95</td>   
                        <td></td>               
                      </tr>
                      <tr>
                        <td>04/09/2017</td>
                        <td>291712</td>
                        <td>PAG BOLETO</td>
                        <td style="color: red">- 7.143,14</td>
                        <td>8.008,81</td>
                        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>
                      <tr>
                        <td>08/09/2017</td>
                        <td>040817</td>
                        <td>COB LOT DH</td>
                        <td style="color: green">+ 1.428,09</td>
                        <td>9.466,90</td>
                        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>
                      <tr>
                        <td style="font-weight: bold;">30/09/2017</td>
                        <td></td>
                        <td style="font-weight: bold;">SALDO FINAL</td>
                        <td>=====</td>
                        <td style="font-weight: bold;">R$ 9.466,90</td>                  
                        <td></td>
                      </tr>                
                    </table>                                        
                  </section>
                </div>
                <!-- Fim conteúdo ContaCorrente-->

                <!-- Início conteúdo ContaPoupanca-->
                <div class="tab-pane" id="cpBB">
                  <section id="new">
                    <div>
                      <h5>Banco: <img style="width: 20px;" src="Views/Sistema/admin/images/bb.png" alt="bb"> <b>Banco do Brasil</b></h6>
                      <h5>Cliente: <b>Condomínio Residencial AAAAAA</b></h5>
                      <h5>Conta: <b>1234 / 013 / 12345678-9</b></h5>
                      <h5>Data: <b>01/10/2017 - 12:10</b></h5>          
                      <h5>Mês: <b>Setembro/2017</b></h5>
                    </div>
                    <button type="button" class="btn btn-block btn-info"><i class="fa fa-fw fa-cloud-upload"></i> Importar Extrato</button>
                    <table class="table table-striped">
                      <tr>
                        <th>Data</th>
                        <th>Num. Doc.</th>
                        <th>Descrição</th>
                        <th>Valor</th>
                        <th>Saldo</th>
                        <th style="width: 10px"></th>
                      </tr>
                      <tr>
                        <td style="font-weight: bold;">01/09/2017</td>
                        <td></td>
                        <td style="font-weight: bold;">SALDO ANTERIOR</td>
                        <td>=====</td>
                        <td style="font-weight: bold;">R$ 20.338,79</td>   
                        <td></td>               
                      </tr>
                      <tr>
                        <td>03/09/2017</td>
                        <td>000000</td>
                        <td>REM BASICA</td>
                        <td style="color: green">+ 3,18</td>
                        <td>20.341,97</td>
                        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>
                      <tr>
                        <td>04/09/2017</td>
                        <td>001550</td>
                        <td>DEB.AUTOR.</td>
                        <td style="color: red">- 16.000,00</td>
                        <td>4.341,97</td>
                        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>                      
                      <tr>
                        <td>08/09/2017</td>
                        <td>608000</td>
                        <td>CONV608000</td>
                        <td style="color: green">+ 32.000,00</td>
                        <td>36.341,97</td>
                        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                      </tr>
                      <tr>
                        <td style="font-weight: bold;">30/09/2017</td>
                        <td></td>
                        <td style="font-weight: bold;">SALDO FINAL</td>
                        <td>=====</td>
                        <td style="font-weight: bold;">R$ 36.341,97</td>                  
                        <td></td>
                      </tr>                
                    </table>                                                                              
                  </section>
                </div>
                <!-- Fim conteúdo ContaPoupanca-->
              </div>
              <!-- Fim conteúdo Contas-->
            </div> 
            <!-- Fim Contas-->  

            </section>
          </div>
          <!-- Fim conteúdo Extrato-->

          <!-- Inicio Despesas a Compensar-->
          <div class="tab-pane" id="despesas">
            <section id="new">              
              <table class="table table-striped">
                <tr>
                  <th>Data</th>
                  <th>Num. Doc.</th>
                  <th>Descrição</th>
                  <th>Valor</th>
                  <th style="width: 10px"></th>
                </tr>
                <tr>
                  <td>03/09/2017</td>
                  <td>902109</td>
                  <td>Cheque - MB Vidros</td>
                  <td>1.463,87</td>
                  <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                </tr>                
                <tr>
                  <td></td>
                  <td></td>
                  <td style="font-weight: bold;">TOTAL</td>                  
                  <td style="font-weight: bold; color: red">R$ 1.463,87</td>                  
                  <td></td>
                </tr>                
              </table>                                                                              
            </section>
          </div>                    
          <!-- Fim Despesas a Compensar-->

          <!-- Inicio Carteira de Conbrança-->
          <div class="tab-pane" id="carteira">
          <section id="new">              
              <table class="table table-striped">
                <tr>
                  <th>Data</th>
                  <th>Num. Doc.</th>
                  <th>Descrição</th>
                  <th>Valor</th>
                  <th style="width: 10px"></th>
                </tr>
                <tr>
                  <td>07/09/2017</td>
                  <td>1014B072018</td>
                  <td>Recebimento de Acordo</td>
                  <td>1.463,87</td>
                  <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                </tr>          
                <tr>
                  <td>10/09/2017</td>
                  <td>1044B072018</td>
                  <td>Recebimento de Acordo</td>
                  <td>2.365,23</td>
                  <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                </tr>  
                <tr>
                  <td>01/09/2017</td>
                  <td>3062EB062018</td>
                  <td>Taxa de Condominio</td>
                  <td>266,74</td>
                  <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                </tr>                                        
                <tr>
                  <td></td>
                  <td></td>
                  <td style="font-weight: bold;">TOTAL</td>                  
                  <td style="font-weight: bold; color: green">R$ 4.095,84</td>                  
                  <td></td>
                </tr>                
              </table>                                                                              
            </section>
          </div>              
          <!-- Fim Carteira de Conbrança-->

        </div>
        <!-- Fim conteúdo-->          
    </div>
   <!-- Fim Prestação/Extrato-->       
  </div>
</section>

