<!--?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();       
?-->
<!-- Inicio Despesas a Compensar-->
<div class="tab-pane active" id="despesas">
  <section id="new">
    <table class="table table-striped">
      <tr>
        <th>Data</th>
        <th>Num. Doc.</th>
        <th>Descrição</th>
        <th>Valor</th>
        <th style="width: 10px"></th>
      </tr>
      <tr>
        <td>03/09/2017</td>
        <td>902109</td>
        <td>Cheque - MB Vidros</td>
        <td>1.463,87</td>
        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
      </tr>
      <tr>
        <td>07/09/2017</td>
        <td>902110</td>
        <td>Cheques - Parcela 1/4 - DELL Computadores</td>
        <td>2.024,66</td>
        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
      </tr>
      <tr>
        <td>07/09/2017</td>
        <td>902111</td>
        <td>Cheques - Parcela 2/4 - DELL Computadores</td>
        <td>2.024,66</td>
        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
      </tr>
      <tr>
        <td>07/09/2017</td>
        <td>902112</td>
        <td>Cheques - Parcela 3/4 - DELL Computadores</td>
        <td>2.024,66</td>
        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
      </tr>
      <tr>
        <td>07/09/2017</td>
        <td>902113</td>
        <td>Cheques - Parcela 4/4 - DELL Computadores</td>
        <td>2.024,66</td>
        <td><button type="button" title="Detalhar" class="btn btn-block btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td style="font-weight: bold;">TOTAL</td>
        <td style="font-weight: bold; color: red">R$ 9.562,51</td>
        <td></td>
      </tr>
    </table>
  </section>
</div>
<!-- Fim Despesas a Compensar-->