<!--?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();       
?-->

<section class="content-header">
  <h1>
    Previsão de Despesas
  </h1>
</section>

<section class="content">
  <div class="row"> 
    <!-- Início Período-->
    <div class="col-xs-4" style="min-width: 400px;">
      <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="box-title">Período</h3>                      
        </div>

        <div class="box-body">
          <div class="col-md-16">

          <!-- Início Ano-->
            <div class="form-group" style="width: 100px; float:left; margin-right:10px;">
              <label>Ano</label>
              <select class="form-control select2">
                <option selected="selected">2018</option>
                <option>2017</option>
                <option>2016</option>
                <option>2015</option>
              </select>
            </div>
           <!-- Fim Ano--> 
           <!-- Início Mês-->
            <div class="form-group" style="width: 100px; float:left;">
              <label>Mês</label>
              <select class="form-control select2">
                <option selected="selected">12</option>
                <option>11</option>
                <option>10</option>
                <option>09</option>
                <option>08</option>
                <option>07</option>
                <option>06</option>
                <option>05</option>
                <option>04</option>
                <option>03</option>
                <option>02</option>
                <option>01</option>
              </select>
            </div>
            <!-- Fim Mês-->
            <!-- Início Botões-->
            <div class="row" style="width: 40px; float:left; margin-left:10px;">
              <button type="button" title="Iniciar Nova Previsão" class="btn btn-block btn-success"><i class="fa fa-plus"></i></button>
              <button type="button" title="Buscar Previsão" class="btn btn-block btn-info"><i class="fa fa-search"></i></button>
            </div>
            <div class="row" style="width: 40px; float:left; margin-left:25px;">
              <button type="button" title="Imprimir Previsão" class="btn btn-block btn-primary"><i class="fa fa-print"></i></button>
            </div>
            <!-- Fim Botões-->

          </div>
        </div>
      </div>
    </div>
    <!-- Fim Período-->
  </div> 

  <div class="row"> 
    <!-- Início Previsão Despesas-->
    <div class="col-xs-12">
      <div class="box box-default">

        <!-- Início Botões Adicionar, Mostrar CheckBox, Fixar e configurar Fundo Reserva-->
        <div class="box-header">
          <button type="button" class="fa fa-plus btn btn-primary" data-toggle="modal" data-target="#myModal">
            Adicionar item
          </button>

          <div class="icone-desp">
            <!--Botão de Exibir Checkbox-->
            <button type="button" id="select-itens" class="btn btn-default"><i class="glyphicon glyphicon-th-list"></i></button>
            <!--Botão de fixar-->
            <button type="button" class="btn btn-default"><i class="glyphicon glyphicon-pushpin"></i></button>
            <!--Botão de Configuração-->
            <button type="button" class="btn btn-default" data-toggle="modal" data-target="#myConfig"><i class="glyphicon glyphicon-cog"></i></button>
          </div>
        </div>
        <!-- Fim Botões Adicionar, Mostrar CheckBox, Fixar e configurar Fundo Reserva-->

        <!-- Início Tabela Previsão de Despesas-->
        <div class="box-body">
          <div class="col-md-16">

            <div id="encontrarPrevisao" >
              <!--Tabela-->
              <div class="table-responsive">
                <table class="table table-striped no-margin">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Despesa</th>
                    <th>Valor</th>
                    <th>Descrição</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody id="bodyTable">

                </tbody>
                <tfoot id="footTable">
                  <tr>
                    <th colspan="2">Sub-Total</td>
                    <th id="subTotal"></th>
                    <th colspan="2"></th>
                  </tr>
                  <tr>
                    <th colspan="2">Fundo de Reserva</th>
                    <th id="fundoReserva"></th>
                    <th colspan="2"></th>
                  </tr>
                  <tr>
                    <th colspan="2">Total</th>
                    <th id="total"></th>
                    <th colspan="2"></th>
                  </tr>
                </tfoot>              
                </table>
              </div>
            </div>
          </div>

          <hr/>

          <div class="row" style="width: 40px; float:right; margin-right:25px;">
            <button type="button" title="Emitir Taxa de Condomínio" class="btn btn-block btn-danger"><i class="fa fa-save"></i></button>
          </div>

        </div>
      </div>
    </div>
    <!-- Fim Taxa de condominio-->
  </div>  
</section>

<script>
  //mascara inputmask, ERRO= não muda dinamicamente quando add outros
  $(document).ready(function () {
    $("#valor").inputmask({
      'alias': 'decimal',
      'groupSeparator': '',
      'digits': 2,
      'autoGroup': true,
      'digitsOptional': false,
      rightAlign: true,
      numericInput: true
    });

    //valor invalido na mascara
    Inputmask.extendDefaults({
      onKeyValidation: function (key, result) {
        if (!result) alert('Valor inválido');
      }
    });

    $('.combobox').combobox();
  });

  //iCheck for checkbox and radio inputs
  $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
    checkboxClass: 'icheckbox_minimal-blue',
    radioClass: 'iradio_minimal-blue'
  })

  $('#select_all').click(function (event) {
    if (this.checked) {
      // Iterate each checkbox
      $(':checkbox').each(function () {
        this.checked = true;
      });
    }
    else {
      $(':checkbox').each(function () {
        this.checked = false;
      });
    }
  });

  $('#adicionar-item').click(function () {
    var valorDespesa = $('#valor').val();
    var desc = $('#descricao').val();
    var comboBox;
    var novoID;
    var subTotal = 0;
    var inputFundoReserva = $('#inputValorFdReserva').val();
    var fundoReserva;

    $("#combo option:selected").each(function () {
      comboBox = $(this).val();
    });

    if (!$('#bodyTable tr:last td').length) novoID = 1;
    else novoID = parseFloat($('#bodyTable tr:last td').html()) + 1;

    //adicionando linha na tabela
    $('#bodyTable').append(
      '<tr class="demo" id="tr_' + novoID + '">' +
      '   <td>' + novoID + '<input type="checkbox"></td>' +
      '   <td>' + comboBox + '</td>' +
      '   <td class="valor-unit-desp">' + valorDespesa + '</td>' +
      '   <td>' + desc + '</td>' +
      '   <td>' +
      '       <i class="glyphicon glyphicon-pencil"></i>' +
      '       <button type="button" class="btn btn-default btn-linha" style="padding: 0;" data-toggle="modal" data-target="#myConfig' + novoID + '">' +
      '           <i class="glyphicon glyphicon-trash"></i>' +
      '       </button>' +
      '   </td>' +
      '</tr>');

    $('<div class="modal fade" id="myConfig' + novoID + '" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">' +
      '<div class="modal-dialog" role="document">' +
      '  <div class="modal-content">' +
      '    <div class="modal-body">' +
      '       <p>Tem certeza que deseja excluir este item?</p>' +
      '    </div>' +
      '    <div class="modal-footer">' +
      '      <button id="lixo_' + novoID + '" type="button" onClick="excluirLinha(\'#tr_' + novoID + ', #myConfig' + novoID + ', .in\');" class="btn btn-danger" data-dismiss="modal" >' +
      '        Sim' +
      '      </button>' +
      '      <button type="button" data-dismiss="modal" class="btn btn-default">' +
      '         Não' +
      '      </button>' +
      '    </div>' +
      '  </div>' +
      '</div>' +
      '</div>' +
      '</div>').insertBefore('table');

    $('#footTable').css("visibility", "visible");
    $('.demo td:first-child input[type="checkbox"]').css("visibility", $("#select-itens").val()); //Só Exibe o checkbox quando clicar no iconeFixar

    //Atualiza Valores SubTotal, Fundo reserva e Total
    calcularValores();
  });


  //Quando clicar no botao select-itens Mostra/Esconde o checkbox
  $('#select-itens').click(function () {
    if ($("#select-itens").val() == "visible") $("#select-itens").val("hidden");
    else $("#select-itens").val("visible");

    $('.demo td:first-child input[type="checkbox"]').css("visibility", $("#select-itens").val()); //Só Exibe o checkbox quando clicar no iconeFixar
  });
</script>