<?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();       
?>
<div class="modal modal-default fade" id="modal-default" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span></button>
        <h4 class="modal-title"><?= $valores['header']?></h4>
      </div>
      <div class="modal-body">
        <div id="box">
          <div class="form-group col-md-12">

            <div style="width: 20vw;" class="input-group input-group-sm">
              <input type="text" class="form-control" id="inputCond" placeholder="Informe o CNPJ/Nome Condomínio">
              <span class="input-group-btn">
              <a href="/" data-dismiss="modal"onClick='requisitarServidor("index.php", "Condominios.condominio", "route=adicionar", "body_resposta"); return false;' class="btn btn-info"><i class="fa fa-plus"></i></a>               
              </span>
              
            </div>

            <hr />

            <select multiple class="form-control" id="listaCond">
              <?php foreach ($valores['dados'] as $key => $condominio) { ?>    
                <option><?= $condominio['cnpj']?> | <?= $condominio['nome']?></option>
              <?php }?>             
              
            </select>

            <hr />

            <div id="actions" class="row">
              <div class="col-md-12">
                <a href="/" data-dismiss="modal" onClick='requisitarServidor("index.php", "Condominios.mudarCond", "cond="+$("#listaCond option:selected").text(), "modal_resposta"); $(".in").remove(); return false; ' class="btn btn-primary">Escolher</a>
              </div>
            </div>
            
          </div>
          <div style="clear: both;"></div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>        
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<script>
  $('#modal-default').modal();


  //Filtro
  $(function(){
      $("#inputCond").keyup(function(){
          var texto = $(this).val();
          
          $("#listaCond option").css("display", "block");
          $("#listaCond option").each(function(){
              if($(this).text().indexOf(texto) < 0)
                $(this).css("display", "none");
          });
      });
  });
</script>
