<!--?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();       
?-->
<section class="content-header">
  <h1>
    Taxa de Condomínio
  </h1>
</section>
<section class="content">
  <div class="row"> 
    <!-- Início Período-->
    <div class="col-xs-4" style="min-width: 400px;">
      <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="box-title">Período</h3>                      
        </div>

        <div class="box-body">
          <div class="col-md-16">

          <!-- Início Ano-->
            <div class="form-group" style="width: 100px; float:left; margin-right:10px;">
              <label>Ano</label>
              <select class="form-control select2">
                <option selected="selected">2018</option>
                <option>2017</option>
                <option>2016</option>
                <option>2015</option>
              </select>
            </div>
           <!-- Fim Ano--> 
           <!-- Início Mês-->
            <div class="form-group" style="width: 100px; float:left;">
              <label>Mês</label>
              <select class="form-control select2">
                <option selected="selected">12</option>
                <option>11</option>
                <option>10</option>
                <option>09</option>
                <option>08</option>
                <option>07</option>
                <option>06</option>
                <option>05</option>
                <option>04</option>
                <option>03</option>
                <option>02</option>
                <option>01</option>
              </select>
            </div>
            <!-- Fim Mês-->
            <!-- Início Botões-->
            <div class="row" style="width: 40px; float:left; margin-left:10px;">
              <button type="button" title="Iniciar Nova Previsão" class="btn btn-block btn-success"><i class="fa fa-plus"></i></button>
              <button type="button" title="Buscar Previsão" class="btn btn-block btn-info"><i class="fa fa-search"></i></button>
            </div>
            <div class="row" style="width: 40px; float:left; margin-left:25px;">
              <button type="button" title="Imprimir Previsão" class="btn btn-block btn-primary"><i class="fa fa-print"></i></button>
            </div>
            <!-- Fim Botões-->

          </div>
        </div>
      </div>
    </div>
    <!-- Fim Período-->
  </div> 

  <div class="row"> 
    <!-- Início Taxa de Condominio-->
    <div class="col-xs-12">
      <div class="box box-default">
        <div class="box-body">
          <div class="col-md-16">

            <div id="encontrarPrevisao" >
              <!--Tabela-->
              <div class="table-responsive">
                <table class="table table-striped no-margin">
                  <thead>
                  <tr>
                    <th>Bloco</th>
                    <th>Ap</th>
                    <th>Nome</th>
                    <th>Valor</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody id="bodyTable">
                  <tr>
                    <td>A</td>
                    <td>201</td>
                    <td>Maria Francisca Silva</td>
                    <td>150,00</td>
                    <td>                      
                      <button type="button" title="Detalhar"     style="padding:1px; width:auto; float: left; margin-right:10px;" class="btn btn-primary"><i class="fa fa-fw fa-info"></i></button>
                      <button type="button" title="Enviar Email" style="padding:1px; width:auto; float: left;" class="btn btn-success"><i class="fa fa-fw fa-envelope"></i></button>
                    </td>
                  </tr>
                  <tr>
                    <td>A</td>
                    <td>505</td>
                    <td>Joaquim Barbosa Filho</td>
                    <td>150,00</td>
                    <td>                      
                      <button type="button" title="Detalhar"     style="padding:1px; width:auto; float: left; margin-right:10px;" class="btn btn-primary"><i class="fa fa-fw fa-info"></i></button>
                      <button type="button" title="Enviar Email" style="padding:1px; width:auto; float: left;" class="btn btn-success"><i class="fa fa-fw fa-envelope"></i></button>
                    </td>
                  </tr>
                  <tr>
                    <td>C</td>
                    <td>102</td>
                    <td>Antonele Fontinele Duarte</td>
                    <td>100,00</td>
                    <td>                      
                      <button type="button" title="Detalhar"     style="padding:1px; width:auto; float: left; margin-right:10px;" class="btn btn-primary"><i class="fa fa-fw fa-info"></i></button>
                      <button type="button" title="Enviar Email" style="padding:1px; width:auto; float: left;" class="btn btn-success"><i class="fa fa-fw fa-envelope"></i></button>
                    </td>
                    
                  </tr>
                  <tr>
                      <td>C</td>
                      <td>102</td>
                      <td>Marcelo Farias Souza</td>
                      <td>Isento</td>
                      <td>                      
                        <button type="button" title="Detalhar"     style="padding:1px; width:auto; float: left; margin-right:10px;" class="btn btn-primary"><i class="fa fa-fw fa-info"></i></button>
                        <button type="button" title="Enviar Email" style="padding:1px; width:auto; float: left;" class="btn btn-success"><i class="fa fa-fw fa-envelope"></i></button>
                      </td>
                    </tr>
                </tbody>                
                </table>
              </div>
            </div>
          </div>

          <hr/>

          <div class="row" style="width: 40px; float:right; margin-right:25px;">
            <button type="button" title="Imprimir Previsão" class="btn btn-block btn-danger"><i class="fa fa-save"></i></button>
          </div>

        </div>
      </div>
    </div>
    <!-- Fim Taxa de condominio-->
  </div>  
</section>