<!--?php
    //Pega as variáveis para renderizar a página
    $valores = $this->getHTMLValores();       
?-->
<section class="content-header">
  <h1>
    Usuários    
  </h1>
</section>
<section class="content">
<div class="row"> 

<!-- Início Consulta-->
<div class="col-xs-2" style="width: 380px;">
  <div class="box box-default">
    <div class="box-header with-border">
      <h3 class="box-title">Pesquisar</h3>                      
    </div>
    <div class="box-body">
      <div class="col-md-16">
        <!-- Início Grupo-->
        <div class="form-group consulta-group">
          <div class="input-group">
            <!-- Input consulta-->
            <input type="text" class="form-control search-input" id="global-search" type="search" placeholder="Digite o filtro...">
            <!-- Botão consulta-->
            <span class="input-group-btn">
              <button type="button" class="btn btn-primary"><i class="fa fa-fw  fa-search"></i></button>
            </span>
          </div>
        </div>
       <!-- Fim Grupo-->                      
        </div>
      </div>
    </div>
  </div>
  <!-- Fim Consulta-->
</div> 

  <div class="row"> 
    <!-- Início CAtegoria-->
    <div class="col-xs-12">
      <div class="box box-default">
        <div class="box-body">
          <div class="col-md-16">

            <div id="encontrarPrevisao" >
              <!--Tabela-->
              <div class="table-responsive">
                <table class="table table-striped no-margin">
                  <thead>
                  <tr>
                    <th>Usuário</th>
                    <th>Nome</th>
                    <th>Perfil</th>
                    <th>Último acesso</th>
                    <th>Status</th>
                    <th><button type="button" title="Novo"     style="padding:5px; width:auto; float: left;" class="btn btn-success"><i class="fa fa-fw fa-plus"></i></button></th>
                  </tr>
                </thead>
                <tbody id="bodyTable">
                  <tr>
                    <td>jaa020399@gmail.com</td>
                    <td>Jônathas Assunção Alves</td>
                    <td>Operador</td>
                    <td>19/10/2018 14:26</td>
                    <td>ATIVO</td>
                    <td><button type="button" title="Detalhar"     style="padding:1px; width:auto; float: left;" class="btn btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                  </tr>
                  <tr>
                    <td>dominic.rp.s2@gmail.com</td>
                    <td>Dominic Rocha</td>
                    <td>Administrador</td>
                    <td>19/10/2018 14:26</td>
                    <td><b>INATIVO</b></td>
                    <td><button type="button" title="Detalhar"     style="padding:1px; width:auto; float: left;" class="btn btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                  </tr>
                  <tr>
                    <td>ADMIN</td>
                    <td>David Antônio</td>
                    <td>Usuário</td>
                    <td> - </td>
                    <td>ATIVO</td>
                    <td><button type="button" title="Detalhar"     style="padding:1px; width:auto; float: left;" class="btn btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                  </tr>
                  <tr>
                    <td>jaderhfa@hotmail.com</td>
                    <td>Jader Henrique Faria Amorim</td>
                    <td>Administrador</td>
                    <td>15/10/2018 14:26</td>
                    <td>ATIVO</td>
                    <td><button type="button" title="Detalhar"     style="padding:1px; width:auto; float: left;" class="btn btn-primary"><i class="fa fa-fw fa-info"></i></button></td>
                  </tr>
                </tbody>                
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Fim Categoria-->
  </div>  

</section>