START TRANSACTION;
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `banco` ADD `cnpj` VARCHAR(14) NOT NULL AFTER `agencia`;
ALTER TABLE `banco` ADD CONSTRAINT `Fk_BancoCondominio` FOREIGN KEY (`cnpj`) REFERENCES `condominio`(`cnpj`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `cazulo`.`banco` DROP PRIMARY KEY, ADD PRIMARY KEY (`operacao`, `conta`, `agencia`, `cnpj`) USING BTREE;
SET FOREIGN_KEY_CHECKS=1;
COMMIT;


