<!DOCTYPE html>
<html lang="pt-br">

<head>
	<title>Sistema de Administração de Condomínios</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">


	<!--========================================	CSS		==========================================-->
	<link rel="icon" type="image/png" href="Views/Login/images/icons/favicon.ico" />
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="Views/Login/vendor/bootstrap/css/bootstrap.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="Views/Login/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	<!--===============================================================================================-->

	<link rel="stylesheet" type="text/css" href="Views/Login/css/util.css">
	<link rel="stylesheet" type="text/css" href="Views/Login/css/main.css">
	<link rel="stylesheet" type="text/css" href="Views/Login/css/login_css.css">
	<link rel="stylesheet" type="text/css" href="Views/css/global_css.css">
	<!--===============================================================================================-->


	<!--====================================  RECAPTCHA   =============================================-->
	<script src='https://www.google.com/recaptcha/api.js'></script>
	<!--===============================================================================================-->
</head>

<body>

	<div class="limiter">
		<div class="container-login100" style="background-image: url('Views/Login/images/bg-01.jpg');">
			<div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
				<form class="login100-form validate-form flex-sb flex-w">
					<span class="login100-form-title p-b-53">
						<img style="width: 15%" src="Views/Login/images/icons/favicon.ico" alt="Cazulo">
						C<span style="color:#0f8cd6">azul</span>o
					</span>

					<span class="login100-form-title p-b-53" style="font-size: 20px">
						Sistema de Administração de Condomínios
					</span>
					
					<!-- Div recebe que recebe resposta do servidor-->
					<div class="login100-form-title" id="body_res">						
					</div>

					<a href="#" class="btn-face m-b-20">
						<i class="fa fa-facebook-official"></i>
						Facebook
					</a>

					<a href="#" class="btn-google m-b-20">
						<img src="Views/Login/images/icons/icon-google.png" alt="GOOGLE">
						Google
					</a>

					<div class="p-t-31 p-b-9">
						<span class="txt1">
							Usuário
						</span>
					</div>
					<div class="wrap-input100 validate-input" data-validate="Usuário obrigatório!">
						<input class="input100" type="text" id="usuario" name="usuario" value="ADMIN">
						<span class="focus-input100"></span>
					</div>

					<div class="p-t-13 p-b-9">
						<span class="txt1">
							Senha
						</span>

						<a href="#" class="txt2 bo1 m-l-5">
							Esqueceu?
						</a>
					</div>
					<div class="wrap-input100 validate-input" data-validate="Senha obrigatório!">
						<input class="input100" type="password" id="senha" name="senha" value="123">
						<span class="focus-input100"></span>
					</div>

					<div class="p-t-13 p-b-9 g-recaptcha" data-sitekey="6LeVunEUAAAAADwwK5zqtq92NG6NLOqzrFdlQH3e"></div>

					<div class="container-login100-form-btn m-t-17">
						<button id="btLogar" class="login100-form-btn">
							Entrar
						</button>
					</div>
					<div id="load_div"></div>
				</form>
			</div>
		</div>
	</div>

	<!--===============================================================================================-->
	<script src="Views/Login/vendor/jquery/jquery-3.2.1.min.js"></script>
	<!--===============================================================================================-->
	<script src="Views/Login/js/main.js"></script>
	<script src="Views/js/global_js.js"></script>
	<script src="Views/Login/js/login_js.js"></script>
</body>
</html>